### ISSUE TITLE
Table selection throwing an exception occasionally

### ISSUE THREAD

**Issue by anddrzejb** [ant-design-blazor/ant-design-blazor#1138]
I have a weird problem. So I use the table component for users to select specific records. Most of the time everything works, but every now and then I get an exception:
```
System.InvalidOperationException: Unable to set property 'SelectedRows' on object of type 'AntDesign.Table`1[[TransportationShared.Dtos.Fare.SettlementDto, TransportationShared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. The error was: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AntDesign.Table`1.set_SelectedRows(IEnumerable`1 value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
```
The rest of the exception is blazor stuff, so I omitted it. Anyways, I couldn't figure it out until I actually got a very similar exception but this time with code line that pointed me to the possible offender:
```
System.InvalidOperationException: Unable to set property 'SelectedRows' on object of type 'AntDesign.Table`1[[TransportationShared.Dtos.Fare.SettlementDto, TransportationShared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. The error was: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AntDesign.Table`1.set_SelectedRows(IEnumerable`1 value) in D:\dotnet\AntDesignBlazor\Forked\Components\components\table\Table.razor.Selection.cs:line 17
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
```
So, there is this part `Table.razor.Selection.cs` where `SelectedRows` property is set (the offending line 17): 
```csharp
15   if (value != null && value.Any())
16   {
17      _dataSourceCache.Values.ForEach(x => x.Selected = x.Data.IsIn(value));
18   }
```
As far as I can tell, the problem is with `_dataSourceCache` (in file `Table.razor.RowData.cs`). 
This private field is only declared and initialization happens only in `FlushCache()`:
```csharp
        private IDictionary<int, RowData<TItem>> _dataSourceCache;

        private void FlushCache()
        {
            if (_dataSourceCache == null)
            {
                _dataSourceCache = new Dictionary<int, RowData<TItem>>();
            }
            else
            {
                _dataSourceCache.Clear();
            }
        }
```

 Currently I am running in production a modification:
```csharp
        private IDictionary<int, RowData<TItem>> _dataSourceCache = new Dictionary<int, RowData<TItem>>();

        private void FlushCache()
        {
            _dataSourceCache.Clear();
        }
```

This modification I made seem to me more exception-proof. The problem is I cannot seem to recreate the situation when the exception is created, thus my change is only an educated guess. Any ideas how I could track it better?

**Comment by ElderJames** [comment]
Could you try to create the instance in the setter of SelectedRows?

```
        [Parameter]
        public IEnumerable<TItem> SelectedRows
        {
            get => _selectedRows;
            set
            {
                _dataSourceCache ??= new Dictionary<int, RowData<TItem>>();

                if (value != null && value.Any())
                {
                    _dataSourceCache.Values.ForEach(x => x.Selected = x.Data.IsIn(value));
                }
                else if (_selectedRows != null)
                {
                    _dataSourceCache.Values.ForEach(x => x.Selected = false);
                }

                _selectedRows = value;

                StateHasChanged();
            }
        }
```

**Comment by anddrzejb** [comment]
Sure, I will try it and report the results. Out of curiosity - what is the difference? Is dictionary memory allocation is so heavy? Because I cannot think about any other advantage. 
On a side note, since I introduced this change, the errors stopped popping up.
