### ISSUE TITLE
Tree Table Sorting Broken

### ISSUE THREAD

**Issue by JosefRousal** [ant-design-blazor/ant-design-blazor#1157]
### Describe the bug

When setting the sortable property on a column of a tree table to true and then trying to change the sort order of the column while the program is running a null reference exception is thrown.

#### Model Class
```
private class TreeNode
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public string Type { get; set; }
    public string Status { get; set; }
    public decimal? Util { get; set; }
    public decimal? Waste { get; set; }
    public List<TreeNode> Children { get; set; }
}
```

#### Component Code
```
<Table DataSource="_treeData" TreeChildren="node => node.Children" Size="TableSize.Small">
    <Column Field="@context.Name" Title="Name"/>
    <Column Field="@(context.Util ?? decimal.Zero)" Title="Util." Format="P" Sortable="true"  DefaultSortOrder="SortDirection.Descending"/>
    <Column Field="@(context.Waste ?? decimal.Zero)" Title="Waste" Format="F"/>
    <ActionColumn Width="200">
        <Space>
            <SpaceItem>
                  <Button Type="default" Size="small"">Action 1</Button>
              </SpaceItem>
              <SpaceItem>
                  <Button Type="default" Size="small">Action 2</Button>
              </SpaceItem>
        </Space>
    </ActionColumn>
</Table>
```

### Exceptions (if any)

```
[10:36:30 ERR] Unhandled exception in circuit 'ofcVjhH6UFA5dkiKz2s0vIPuFNFl_DJXIpPLscBBIPE'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at AntDesign.Column`1.SetSorter(SortDirection sortDirection)
   at AntDesign.Column`1.HandelHeaderClick()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
```

### Further technical details
- AntDesign Nuget Package version: 0.7.0-nightly-2102220638

**Comment by ElderJames** [comment]
Thanks for contacting us @JosefRousal . We will take a look at it.

**Comment by ElderJames** [comment]
Hi @JosefRousal , please use `@bind-Field` or `DataIndex` to specify the properties.

**Comment by JosefRousal** [comment]
Using `@bind-Field` seems to have fixed the problem, thanks.
