### ISSUE TITLE
Table setting fixed column (Fixed="left", Fixed="right", ScrollX="1500") attributes, add multiple selection (<Selection />) error

### ISSUE THREAD

**Issue by DavidStrive** [ant-design-blazor/ant-design-blazor#1167]
Table setting fixed column (Fixed="left", Fixed="right", ScrollX="1500") attributes, add multiple selection (<Selection />)
 error：
[2021-02-24T08:59:47.288Z] Error: System.FormatException: One of the identified items was in an invalid format.
   at AntDesign.CssSizeLength..ctor(String value)
   at AntDesign.CssSizeLength.op_Implicit(String value)
   at AntDesign.Selection.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by ElderJames** [comment]
Hi @DavidStrive ,could you please show your code here?
