### ISSUE TITLE
Table has this problem

### ISSUE THREAD

**Issue by DavidStrive** [ant-design-blazor/ant-design-blazor#1172]
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at AntDesign.Column`1.SetSorter(SortDirection sortDirection)
         at AntDesign.Column`1.HandelHeaderClick()
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'DNxC7iNrJ0FlfzQs6cu8i9NTOmm81aCvwkskB65BP4g'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at AntDesign.Column`1.SetSorter(SortDirection sortDirection)
         at AntDesign.Column`1.HandelHeaderClick()
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
System.Threading.Tasks.TaskCanceledException: A task was canceled.

**Comment by ElderJames** [comment]
Hi @DavidStrive , please show your code here.
