### ISSUE TITLE
Table throws error when accessing referenced model

### ISSUE THREAD

**Issue by dennisrahmen** [ant-design-blazor/ant-design-blazor#1210]
### Describe the bug

The table component produces an error when trying to access data that is not directly in the model you specified in "TItem" but is referenced by that model.

So, this works:
`<Column @bind-Field="@context.Startnum"></Column>`

But this does not, since "Reiter" is a reference to the model "Reiter" where "Rname" is defined:
`<Column @bind-Field="@context.Reiter.Rname"></Column>`

Already discussed a few things on the discord server: [Link to discord message](https://discord.com/channels/753358910341251182/753786457306562651/817045574317899826)

### Steps to reproduce (please include code)
[Minimal repo](https://github.com/dennisrahmen/BlazorServerMinRepo)

### Exceptions (if any)
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at iTS_Infoterm.Pages.Index.<>c__DisplayClass0_0.<BuildRenderTree>b__5(RenderTreeBuilder __builder4)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at AntDesign.Table`1[[iTS_Common.DTOs.StarterDTO, iTS_Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__240_5(RenderTreeBuilder __builder6)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Microsoft.AspNetCore.Components.CascadingValue`1[[System.Boolean, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

### Further technical details
- AntDesign Nuget Package 0.7.1
- Visual Studio Community 16.9.0
- Output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]        
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] 

```

**Comment by ElderJames** [comment]
Hi @dennisrahmen , please refer to #986 .

**Comment by anranruye** [comment]
try this:
```C#
@code{
    public class MyChildClass 
    { 
        public string Name { get; set; } 
    }
    public class WeatherForecast 
    { 
        public int Id { get; set; } 
        public MyChildClass User { get; set; } 
    }
}
<Table ...>
    <Column Title="UserName" Field="@context.User?.Name" DataIndex="User.Name" Sortable>@context.User?.Name</Column>
</Table>
```
