### ISSUE TITLE
select component binding enumeration error in 7.x version, 6.0 version normal

### ISSUE THREAD

**Issue by LingDian2019** [ant-design-blazor/ant-design-blazor#1237]
### Describe the bug

select component binding enumeration error in 7.x version, 6.0 version normal

### Steps to reproduce (please include code)
```
<Select DefaultActiveFirstItem 
             DataSource="@(SelectEnumExtension.GetSelect<WCSClient.Services.ThirdPartyTaskStatus>())"
             @bind-Value="@(context.Status)"
              LabelName="Item1"
              ValueName="Item2">
</Select>


        

public static List<Tuple<string, int>> GetSelect<TEnum>(bool initializationData = true) where TEnum : Enum
 {
            List<Tuple<string, int>> selectEnumOptions = new List<Tuple<string, int>>();

            if (!typeof(TEnum).IsEnum)
            {
                selectEnumOptions.Add(new Tuple<string, int>("当前T不是枚举类型", 0));
                return selectEnumOptions;
            }

            if (initializationData)
            {
                selectEnumOptions.Add(new Tuple<string, int>("请选择", 0));
            }

            foreach (FieldInfo field in typeof(TEnum).GetFields())
            {
                if (field.FieldType.IsEnum)
                {
                    object[] attr = field.GetCustomAttributes(typeof(DescriptionAttribute), false);
                    string description = attr.Length == 0 ? field.Name : ((DescriptionAttribute)attr[0]).Description;

                    var value = Convert.ToInt32(field.GetValue(0));
                    if (!initializationData && value <= 0)
                    {
                        break;
                    }

                    selectEnumOptions.Add(new Tuple<string, int>(description, value));
                }
            }

            return selectEnumOptions;
 }

```

### Exceptions (if any)
The error was: Expression of type 'System.Nullable`1[System.Int32]' cannot be used for return type 'System.Nullable`1[WCSClient.Services.ThirdPartyTaskStatus]'

### Further technical details
- AntDesign Nuget Package version ：0.7.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version：VS2019

**Comment by anddrzejb** [comment]
@LingDian2019: I am getting a different error. Can you post the snippet that will include the `Form` & `enum`?

**Comment by anddrzejb** [comment]
@Zonciu There seems to be an issue when `SelectItemPropertyHelper.CreateSetValueFunc` is trying to prep the setter to work with Tuple. It crashes when preparing assignment expression. I cannot figure it out, why and I cannot find any reasonable example with tuples. Can you have a look? I used this self contained snippet to do my tests:
```razor
@using System.ComponentModel
@using System.Reflection
<Select DefaultActiveFirstItem 
             DataSource="@(GetSelect<ThirdPartyTaskStatus>())"
             @bind-Value="@_status"
             TItem="Tuple<string, int>"
             TItemValue="int" 
             LabelName="Item1"
             ValueName="Item2">
</Select>

@code {
    public enum ThirdPartyTaskStatus
    {
        [DescriptionAttribute("Status1_Descr")]
        Status1,
        Status10,
        [DescriptionAttribute("StatusX_Descr")]
        SatusX
    }

    int _status;  

    public static List<Tuple<string, int>> GetSelect<TEnum>(bool initializationData = true) where TEnum : Enum
    {
        List<Tuple<string, int>> selectEnumOptions = new List<Tuple<string, int>>();

        if (!typeof(TEnum).IsEnum)
        {
            selectEnumOptions.Add(new Tuple<string, int>("Current T is not an enumeration type", 0));
            return selectEnumOptions;
        }

        if (initializationData)
        {
            selectEnumOptions.Add(new Tuple<string, int>("please choose", 0));
        }

        foreach (FieldInfo field in typeof(TEnum).GetFields())
        {
            if (field.FieldType.IsEnum)
            {
                object[] attr = field.GetCustomAttributes(typeof(DescriptionAttribute), false);
                string description = attr.Length == 0 ? field.Name : ((DescriptionAttribute)attr[0]).Description;

                var value = Convert.ToInt32(field.GetValue(0));
                if (!initializationData && value <= 0)
                {
                    break;
                }

                selectEnumOptions.Add(new Tuple<string, int>(description, value));
            }
        }

        return selectEnumOptions;
     }
}
```
And the exception:
```log
blazor.server.js:21 [2021-04-08T10:02:44.780Z] Error: System.InvalidOperationException: 
Unable to set property 'ValueName' on object of type 'AntDesign.Select`2[[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Tuple`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'. The error was: Expression must be writeable (Parameter 'left')
 ---> System.ArgumentException: Expression must be writeable (Parameter 'left')
   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at AntDesign.Select.Internal.SelectItemPropertyHelper.<>c__DisplayClass10_0`2.<CreateSetValueFunc>b__0(DelegateCacheKey _) in D:\dotnet\AntDesignBlazor\Forked\Components\components\select\internal\SelectItemPropertyHelper.cs:line 183
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AntDesign.Select.Internal.SelectItemPropertyHelper.CreateSetValueFunc[TItem,TItemValue](String valueName) in D:\dotnet\AntDesignBlazor\Forked\Components\components\select\internal\SelectItemPropertyHelper.cs:line 155
   at AntDesign.Select`2.set_ValueName(String value) in D:\dotnet\AntDesignBlazor\Forked\Components\components\select\Select.razor.cs:line 133
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at AntDesign.AntInputComponentBase`1.SetParametersAsync(ParameterView parameters) in D:\dotnet\AntDesignBlazor\Forked\Components\components\core\Base\AntInputComponentBase.cs:line 250
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by Zonciu** [comment]
Source code is here: 
[Tuple](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Tuple.cs#L227), 
[ValueTuple](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/ValueTuple.cs#L433).
`Tuple` is a class, it's `ItemX` members are readonly Property.
For `ValueTuple`, it's `ItemX` members are field, it is writeable.

However, for now it is only support property member, you must use property member for `ValueName` and `LabelName`. I'm working on support both field and property member.

**Comment by anddrzejb** [comment]
It did not occur to me to look at the source code. I was 100% sure that `Tuple` had setters on properties, that is why I was so surprised. Thanks for pointing that out.

**Comment by anddrzejb** [comment]
@LingDian2019 Change `Tuple` to `ValueTuple` and it should work.
