### ISSUE TITLE
Unhandled exception rendering component: Index was out of range

### ISSUE THREAD

**Issue by mrjohnr** [ant-design-blazor/ant-design-blazor#1251]
Hi
On .NET 5/Ant Design Blazor 0.7.2
I'm trying to use Popover or Tooltip,but got: 
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1[[Rezervari.Client.Models.StareZi, Rezervari.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
   at Rezervari.Client.Pages.sch.Sch.<>c__DisplayClass0_1.<BuildRenderTree>b__1(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at AntDesign.Button.<BuildRenderTree>b__75_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Microsoft.AspNetCore.Components.CascadingValue`1[[AntDesign.Button, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   
```
code used:
   
```
@page "/"
@inherits SchBase
<div>
    @foreach (var g in grila)
    {
                @for (var idxJ = 0; idxJ < g.Zile.Count; idxJ++)
            {
                if (g.Zile[idxJ].DAYS > 0)
                {
                            @if (g.Zile[idxJ].NAME != "")
                            {
                                <Popover Title="Title" Trigger="@(new AntDesign.TriggerType[] { AntDesign.TriggerType.Hover})">
                                    <AntDesign.Button>@g.Zile[idxJ].NAME</AntDesign.Button>
                                </Popover>
                            }

                }
            }
    }
</div>

```
If I replace  popover markup with a simple bootstrap button (  <button class="btn btn-primary">@g.Zile[idxJ].NAME</button>) it works

the same works If I replace 
`<AntDesign.Button>@g.Zile[idxJ].NAME</AntDesign.Button>`
 with a constant string:
`<AntDesign.Button>NAME1</AntDesign.Button>`

thanks

**Comment by mrjohnr** [comment]
I've fixed the error using a simple variable  `name=g.Zile[idxJ].NAME`  then used `<AntDesign.Button>@name</AntDesign.Button>`

**Comment by ElderJames** [comment]
Please try to assign a variable to `idxJ` in the loop. See the official docs please: https://docs.microsoft.com/zh-cn/aspnet/core/blazor/components/?view=aspnetcore-5.0&WT.mc_id=DT-MVP-5003987#child-content

```
    @for (var i = 0; i< g.Zile.Count; idxJ++)
            {
                var idxJ=i;
                if (g.Zile[idxJ].DAYS > 0)
                {
                            @if (g.Zile[idxJ].NAME != "")
                            {
                                <Popover Title="Title" Trigger="@(new AntDesign.TriggerType[] { AntDesign.TriggerType.Hover})">
                                    <AntDesign.Button>@g.Zile[idxJ].NAME</AntDesign.Button>
                                </Popover>
                            }

                }
            }
```
