### ISSUE TITLE
JS interop exception on Avatar content.

### ISSUE THREAD

**Issue by TsakiDev** [ant-design-blazor/ant-design-blazor#1340]
This error does not occur in all computers.

```razor
<AuthorizeView>
    <Authorized>
        <span class="avatar-item ant-dropdown-link" style="cursor: pointer;">
            <Badge Count="_notificationsCount">
                <Avatar Style="@($"background-color: {context.User.Claims.FirstOrDefault(c => c.Type.Equals("Color")).Value}; vertical-align: middle;")" Shape="square" Size="large">
                    @context.User.Identity.Name
                </Avatar>
            </Badge>
        </span>
    </Authorized>
</AuthorizeView>
```

```
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Int32. Path: $.absoluteTop | LineNumber: 0 | BytePositionInLine: 229.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.absoluteTop | LineNumber: 0 | BytePositionInLine: 229.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.Converters.Int32Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadValueCore[TValue](JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
```

### Further technical details
- AntDesign: v0.7.4
- Dotnet Info:
  ```
  .NET SDK (reflecting any global.json):
  Version:   5.0.201
  Commit:    a09bd5c86c

  Runtime Environment:
  OS Name:     Windows
  OS Version:  10.0.19042
  OS Platform: Windows
  RID:         win10-x64
  Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

  Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

  .NET SDKs installed:
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

  .NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  ```
- Visual Studio 2019 16.9.3

**Comment by anddrzejb** [comment]
Wasm or server-side?

**Comment by TsakiDev** [comment]
Server-side

**Comment by anddrzejb** [comment]
I will try to have a look at this. This is a pesky bug - I was already hunting for it multiple times and never managed to recreate it. Would you be willing to help us out in catching it (if I fail to recreate it again)?

**Comment by TsakiDev** [comment]
Sure but even I can't recreate it.
The exact same code on a different computer works.
We only caught it because it occurred on one out of multiple devs.
I will have to use that computer to try and recreate it.

**Comment by anddrzejb** [comment]
Please do...if we could recreate with at least 25% accuracy, that is something we could probably work with...

**Comment by anddrzejb** [comment]
Can you tell me on what browser the bug manifested?

**Comment by TsakiDev** [comment]
Chrome and Edge Chromium. I didn't check Firefox but I can check it tomorrow.

**Comment by anddrzejb** [comment]
No need. The versions of the browsers might be useful though. I still didn't manage to recreate the problem. But I was trying to mess up in such a way to get the same result. This I managed. It seems that every now and then js call to either `document.documentElement` or `element.getBoundingClientRect()` fails and returns `null` or `NaN` or `undefined`. We can check for that and provide a default value. But the values it tries to get (and occasionally fails) are going to be used for rendering purposes, so they might be important. So we either track what is the reason they are not properly returned or we introduce some kind of retry logic. Again, for these tests we need to have access to the machine that actually generates these errors or have a willing person/contributor to perform the tests and either in cooperation or alone find the fix.

**Comment by TsakiDev** [comment]
Sure but I can only do it tomorrow between 06:00 and 14:00 UTC

**Comment by anddrzejb** [comment]
Great, I am available between 06:00 and 13:00 UTC. Maybe we could coordinate over discord or any other suitable for you channel?

**Comment by TsakiDev** [comment]
I can do discord, teams and hangouts.

**Comment by anddrzejb** [comment]
Perfect. You will find me in Ant Design Blazor channel. Msg me anytime it is convinient.

**Comment by TsakiDev** [comment]
Hi can you please send me a link for the channel?

**Comment by anddrzejb** [comment]
This [link](https://discord.com/invite/jqu3Xeq) is also in the main repo page.
