### ISSUE TITLE
Modal: using slider in template causes exception

### ISSUE THREAD

**Issue by JiaChengLuo** [ant-design-blazor/ant-design-blazor#1374]
### Describe the bug

Using slider in modal template causes exception.
在Modal模板中使用Slider组件时会抛出异常。

### Steps to reproduce (please include code)
TestClass.cs
```
public class TestClass
{
    public (double, double) Values { get; set; }
}
```
ModalTemplate.razor
```
@inherits FeedbackComponent<TestClass>

<Slider TValue="(double, double)" DefaultValue="(0,255)" Min="0" Step="1" @bind-Value="@_model.Values"
        Marks="@(new SliderMark[] { new SliderMark(0, "0"), new SliderMark(255, "255") })" Disabled="true" />
@code{
    private TestClass _model;

    protected override void OnInitialized()
    {
        _model = base.Options ?? new TestClass();
        base.OnInitialized();
    }
}
```
Test.razor
```
@inject ModalService ModalService

<Button OnClick="OpenTemplate" Type="primary">Use Template</Button>

@code{
    private ModalRef _modalRef;

    private async Task OpenTemplate()
    {
        var templateOptions = new TestClass();
        templateOptions.Values = (0, 128);

        var modalConfig = new ModalOptions();
        modalConfig.Title = "Basic Form";
        modalConfig.DestroyOnClose = true;
        modalConfig.Width = 500;
        modalConfig.Footer = null;

        modalConfig.AfterClose = () =>
        {
            Console.WriteLine("AfterClose");
            InvokeAsync(StateHasChanged);
            return Task.CompletedTask;
        };

       await ModalService.CreateModalAsync<ModalTemplate, TestClass>(modalConfig, templateOptions);
    }
}
```

### Exceptions (if any)
```
Error: Microsoft.JSInterop.JSException: Cannot read property 'offsetTop' of null
TypeError: Cannot read property 'offsetTop' of null
    at Object.i [as getDomInfo] (https://localhost:5001/_content/AntDesign/js/ant-design-blazor.js:1:754)
    at https://localhost:5001/_framework/blazor.server.js:8:35886
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:35854)
    at https://localhost:5001/_framework/blazor.server.js:1:20053
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:20023)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:18007)
    at e.connection.onreceive (https://localhost:5001/_framework/blazor.server.js:1:11092)
    at WebSocket.i.onmessage (https://localhost:5001/_framework/blazor.server.js:1:39008)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args) in ant-design-blazor\components\core\Base\AntComponentBase.cs:line 85
   at AntDesign.Internal.Overlay.UpdatePosition(Nullable`1 overlayLeft, Nullable`1 overlayTop) in ant-design-blazor\components\core\Component\overlay\Overlay.razor.cs:line 611
   at AntDesign.Tooltip.ChildElementMoved() in ant-design-blazor\components\tooltip\Tooltip.razor.cs:line 59
   at AntDesign.Slider`1.OnAfterRenderAsync(Boolean firstRender) in ant-design-blazor\components\slider\Slider.razor.cs:line 516
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### Further technical details
- AntDesign Nuget Package version 0.8.0
- .NET 5.0
- VS2019

**Comment by zxyao145** [comment]
Hi @JiaChengLuo ,

Please try to initialize the _model in ModalTemplate.razor during initialization, it's like this:
请尝试初始化 _model  在 ModalTemplate.razor 初始化期间。

请在

```c#
@inherits FeedbackComponent<TestClass>

<Slider TValue="(double, double)" DefaultValue="(0,255)" Min="0" Step="1" @bind-Value="@_model.Values"
        Marks="@(new SliderMark[] { new SliderMark(0, "0"), new SliderMark(255, "255") })" Disabled="true" />
@code{
    private TestClass _model = new TestClass()
    {
        Values = (0,0)
    };
}
```

**Comment by JiaChengLuo** [comment]
@zxyao145  
Sorry, there are some errors in my example, and I have fixed them.
I overwrite the `OnInitialized` method, but the problem still exists.

**Comment by zxyao145** [comment]
Could you provide a complete example compressed package of the issue? I can't reproduce your error, whether it's server or WASM mode.

**Comment by JiaChengLuo** [comment]
@zxyao145 
I directly modified ModalTemplateDemo.razor, and then this problem easily occurred.
😂But I created a new project and it is difficult to reproduce this problem.Unless you quickly open and close Modal.
