### ISSUE TITLE
Table: Column Filterable property doesn't work correctly for enum types

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1430]
### Describe the bug

Column `Filterable` property doesn't work correctly for enum types. 

### Workaround

Use `Filters` property instead.

### Steps to reproduce (please include code)

```
<Column @bind-Field="@context.EnumTypeProperty" Filterable />
```
### Exceptions (if any)

      Unhandled exception rendering component: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: InputNumber supports only numeric types.
   at AntDesign.InputNumber`1[[EnumTypeProperty]]..ctor()
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type componentType)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
### Further technical details
- AntDesign Nuget Package version: 0.8.0

**Comment by ElderJames** [comment]
Hi @anranruye , the `Filterable` just let table show the built-in filters, but for now we haven't add the built-in filter for `enum` types.
If you are interested, can you help add the filter for enum?

**Comment by anranruye** [comment]
@ElderJames I'd love to help, but I don't know what the built-in filter for enum types looks like in other versions ant-design, I never used them before. I glanced the documentation of ant-design react and ant-design vue a few minutes ago, but found nothing, do they have some kinds of build-in filters?

**Comment by ElderJames** [comment]
Nope, just we have the built-in filters. For enum, I thinks it would like to be the same as `List` type.

**Comment by anranruye** [comment]
@ElderJames Also, I think there is still a bug. Before we implement the built-in enum filter, a better exception is needed.

**Comment by anranruye** [comment]
@ElderJames eh, what does 'List type' mean?

**Comment by ElderJames** [comment]
Just like setting the `Filters` parameter. Inside the `Column` component, enum `TableFilterType` has two value , List and FieldType, which you can check out.

**Comment by ElderJames** [comment]
Just like setting the `Filters` parameter. Inside the `Column` component, enum `TableFilterType` has two value , List and FieldType, which you can check out.
