### ISSUE TITLE
Rename entries in the filter function of the table (for foreign languages)?

### ISSUE THREAD

**Issue by true-perfect-code** [ant-design-blazor/ant-design-blazor#1556]
### Is your feature request related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/45635963/118845009-b33e2b80-b8cb-11eb-93e1-c9d8eafe723e.png)

### Describe the solution you'd like
Maybe you can do something similar to charts by defining a config? Or you can provide a tag that contains an object with entries, so that everyone can name the entries in the filter list in their own languages.

**Comment by anranruye** [comment]
Thanks for contacting us @true-perfect-code .

You can use localization configuration to rename these entries. See https://antblazor.com/en-US/docs/i18n.

**Comment by true-perfect-code** [comment]
Thanks anranruye for the quick reply.

Setting the localisation does not seem to work for me! Maybe I am making a mistake?

If I set the localisation as suggested in the documentation, this triggers an error. 
![image](https://user-images.githubusercontent.com/45635963/118860605-e4265c80-b8db-11eb-9d70-9d96ff0258df.png)

How did I do it?
1. start the application and set de-DE. This immediately triggers an error (see below).
![image](https://user-images.githubusercontent.com/45635963/118861389-ba216a00-b8dc-11eb-86f8-08333f87f66c.png)

2. if I skip setting the localisation, the application runs. However, everything is displayed in English.

Here is the error, which you should probably also be able to reproduce relatively easily (assuming my code is correct and I am not making a mistake).

![image](https://user-images.githubusercontent.com/45635963/118861829-403db080-b8dd-11eb-85b0-d32e7dfb8ddc.png)

Text format of the error message:
blazor.server.js:21 [2021-05-19T18:00:16.219Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at AntDesign.Column`1.<>c__DisplayClass135_3.<.ctor>b__35(RenderTreeBuilder __builder7)
   at AntDesign.Select`2.<BuildRenderTree>b__339_5(RenderTreeBuilder __builder4)
   at AntDesign.Internal.Overlay.<BuildRenderTree>b__106_2(RenderTreeBuilder __builder3)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
e.log @ blazor.server.js:21
I @ blazor.server.js:10
(anonymous) @ blazor.server.js:10
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:1 [2021-05-19T18:00:16.227Z] Information: Connection disconnected.
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at e.send (blazor.server.js:1)
    at e.sendMessage (blazor.server.js:1)
    at e.sendWithProtocol (blazor.server.js:1)
    at e.send (blazor.server.js:1)
    at Object.endInvokeJSFromDotNet (blazor.server.js:10)
    at blazor.server.js:1

Regards

**Comment by anranruye** [comment]
@true-perfect-code 

I didn't reproduce this error.  I set `CultureInfo.DefaultThreadCurrentUICulture` in the app's startup.cs file and in an event callback method of a component, no excecption is throwed. I guess you are using `CultureInfo.DefaultThreadCurrentUICulture` in a overriden component lifecycle method which may not allow to change the current cultrue but I didn't make more research.

Anyway, this error doesn't matter because `CultureInfo.DefaultThreadCurrentUICulture` is mainly used for blazor wasm project, not blazor server project. For blazor server projects, you should follow https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-5.0#localization-middleware-2 and https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#blazor-server to set cultureInfo.

To rename the filters entries you mentioned, you should also follow this:
```C#
 // Create a `Locale` object
 var zhHK = new Locale { ... };
 // Set an additional language
 LocaleProvider.SetLocale("zh-HK", zhHK);
```
to add or override a language resource. This is because our built-in language resources are not perfect(translation for some entries is not accurate or missing) and you may want to change some entries.

To override an existing language resource, you can use:
```C#
            var locale = LocaleProvider.GetLocale("de-DE");
            locale.Table.FilterOptions.And = "what you need";
```

Feel free to make a pr and help us to improve our language resources. Resources are in this folder: https://github.com/ant-design-blazor/ant-design-blazor/tree/master/components/locales

**Comment by true-perfect-code** [comment]
Thank you for your detailed answer.

I followed the instructions and it does not work when you set Cultur de-DE. It also doesn't work if you use fr-FR, for example.
If you set en-GB or en-US, then no error is triggered!

How to reproduce the error:

1. In Startup.cs I have inserted the following code
![image](https://user-images.githubusercontent.com/45635963/118965846-66109700-b969-11eb-9815-84ddf64595aa.png)

This triggers the error
![image](https://user-images.githubusercontent.com/45635963/118966811-429a1c00-b96a-11eb-9653-454d9330ad2d.png)

2. If I change the code to en-GB or en-US, the filter works (no error is triggered).
![image](https://user-images.githubusercontent.com/45635963/118966146-b4259a80-b969-11eb-8136-c8055372475b.png)

No error, filter opens:
![image](https://user-images.githubusercontent.com/45635963/118966279-df0fee80-b969-11eb-9cbc-931c29b966af.png)

Is it possible that these localisation files still have to be included in the project?

Thanks

**Comment by true-perfect-code** [comment]
of course, no problem. Here is the Json translation in German for the table area:

ENGLISH
  "Table": {
    "filterTitle": "Filter menu",
    "filterConfirm": "OK",
    "filterReset": "Reset",
    "selectAll": "Select current page",
    "selectInvert": "Invert current page",
    "selectionAll": "Select all data",
    "sortTitle": "Sort",
    "expand": "Expand row",
    "collapse": "Collapse row",
    "triggerDesc": "Click sort by descend",
    "triggerAsc": "Click sort by ascend",
    "cancelSort": "Click to cancel sort",
    "filterOptions": {
      "true": "True",
      "false": "False",
      "and": "And",
      "or": "Or",
      "equals": "Equal",
      "notEquals": "Not Equal",
      "contains": "Contains",
      "startsWith": "Start With",
      "endsWith": "End With",
      "greaterThan": "Greater Than",
      "lessThan": "Less Than",
      "greaterThanOrEquals": "Greater Than Or Equals",
      "lessThanOrEquals": "Less Than Or Equals",
      "isNull": "Is Null",
      "isNotNull": "Is Not Null"
    },

GERMAN
    "Table": {
      "filterTitle": "Filter-Menü",
      "filterConfirm": "OK",
      "filterReset": "Zurücksetzen",
      "selectAll": "Selektiere Alle",
      "selectInvert": "Selektion Invertieren",
      "selectionAll": "Wählen Sie alle Daten aus",
      "sortTitle": "Sortieren",
      "expand": "Erweitern",
      "collapse": "Reduzieren",

      "triggerDesc": "Absteigend sortieren",
      "triggerAsc": "Aufsteigend sortieren",
      "cancelSort": "Sortierung löschen",
      "filterOptions": {
        "true": "Wahr",
        "false": "Falsch",
        "and": "Und",
        "or": "Oder",
        "equals": "Gleich",
        "notEquals": "Nicht gleich",
        "contains": "Enthält",
        "startsWith": "Beginnt mit",
        "endsWith": "Endet mit",
        "greaterThan": "Größer als",
        "lessThan": "Kleiner als",
        "greaterThanOrEquals": "Grösser als oder gleich",
        "lessThanOrEquals": "Kleiner als oder gleich",
        "isNull": "Ist leer",
        "isNotNull": "Ist nicht leer"
      }
    }
  }

Regards

**Comment by anranruye** [comment]
@true-perfect-code 

The json files are embeded in the dll file, so you can not edit them. You can wait for the nightly-build version which is updated very fast. Also, you can download the source code and build the project on your local machine.

**Comment by true-perfect-code** [comment]
Thank you, I will wait for the new version. It's not urgent anyway.
