### ISSUE TITLE
Cannot filter table on calculated properties

### ISSUE THREAD

**Issue by dahegit** [ant-design-blazor/ant-design-blazor#1628]
Hi!
I am using the table component like this:
`  <Table TItem="WeatherForecast" DataSource="@forecasts">
        <Column Field="@context.TemperatureF" Filters="tempFilter" OnFilter="((value,name)=>name.Equals(value))">
            <TitleTemplate>
                @nameof(WeatherForecast.TemperatureF)
            </TitleTemplate>
        </Column>
    </Table>`

And the tempFilter is initialized like this:
`  tempFilter = forecasts.AsEnumerable().Select(x => new TableFilter<int> { Text = x.TemperatureF.ToString(), Value = x.TemperatureF }).ToArray();`

If TemperatureF is not a calculated property it works but if TemperatureF is a calculated property like this:
`        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);`

I get the following error:
`blazor.server.js:21 [2021-06-10T08:51:44.110Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at AntDesign.TableModels.FilterModel1.FilterList[TItem](IQueryable1 source)
   at AntDesign.Table1.Reload()
   at AntDesign.Table1.ReloadAndInvokeChange()
   at AntDesign.Table1.AntDesign.ITable.ReloadAndInvokeChange()
   at AntDesign.Column1.FilterConfirm(Boolean isReset)
   at AntDesign.Column1.<>c__DisplayClass135_3.<.ctor>b__42()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback1.InvokeAsync(TValue arg)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`

**Comment by anranruye** [comment]
Thanks for contacting us @dahegit .

You can use `DataIndex` instead of `Field` for a readonly property, like this:
```
...
<Column DataIndex="TemperatureF" Filters="tempFilter" OnFilter="((value,name)=>name.Equals(value))"> 
    <TitleTemplate> @nameof(WeatherForecast.TemperatureF) </TitleTemplate> 
</Column>
...
```

**Comment by dahegit** [comment]
Thank you so much! That worked perfectly! ant-design-blazor is really awesome!
