### ISSUE TITLE
Label for input fields outside form?

### ISSUE THREAD

**Issue by shashikantx** [ant-design-blazor/ant-design-blazor#1725]
Hi, 
I have been using antblazor for two months, it is really great, and I really appreciate the effort being put in to improve it. That being said, I noticed that input fields when used individually outside forms, I am unable to put a label to it because label is part of FormItem. It would be nice if there was a label component.

Thank you.

**Comment by ElderJames** [comment]
Thanks for contacting us @shashikantx 

Please try to use `Space` component for that.

**Comment by shashikantx** [comment]
@shashikantx  Yea, that works, thanks for the workaround.

But still, my suggestion stands, to maintain uniformity in style either a label parameter could be passed to the Input fields or a `<Label></Label>` wraparound component could be created.

Not a big issue, but nice to have out of the box.

**Comment by anranruye** [comment]
@shashikantx generally, we provide `FormItem` component for this purpose, which forces you to use input components inside a form. You can wrap a input component by `<CascadingValue Value="null" Name="FormItem" TValue="IFormItem" IsFixed="@true">` to remove this limitation. Or you can implement your own `Label` component by just copy the source code of `FormItem` component and remove the "FormItem"  `CascadingValue ` (I don't think to modify `FormItem` component directly is a good idea). Official implementation for `Label` component may be late since this issue/feaure may not have a high prioriry. We highly encourage pull request contributions. If you have the ability and interest, feel free to open a pr.

**Comment by shashikantx** [comment]
Ohok understood, Thank you. @anranruye 

I can make a pr for Label component if that's alright.

**Comment by ElderJames** [comment]
Hey @shashikantx , has there been any progress?

**Comment by shashikantx** [comment]
Hi @ElderJames , sorry, I haven't started anything yet.

I will finish by next weekend,

So I had few question. Hope you don't mind answering.

What will be name of the component? 
I am assuming we are going with  `Label` here.

What will be the name namespace for the component?
It won't fall under "form" obviously because it will be independent of it and FormItem already has Label parameter. 
 
Should I just create a folder 'label' and use AntDesign namespace directly? will that be okay?

**Comment by ElderJames** [comment]
I thinks if the Label just for imput-type components, you can make it as a renderfargment of `AntInputComponentBase`

**Comment by shashikantx** [comment]
Okay, I will get on to it.

**Comment by shashikantx** [comment]
@ElderJames @anranruye 
Hi, I am trying to run `npm run` as instructed in docs for development, this is the error facing.

```
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
         at AntDesign.Docs.Services.DemoService.<>c__DisplayClass12_0.<<InitializeAsync>b__0>d.MoveNext() in D:\Projects\opensource\ant-design-blazor\site\AntDesign.Docs\Services\DemoService.cs:line 44
      --- End of stack trace from previous location ---
         at AntDesign.Docs.Services.DemoService.InitializeAsync(String language) in D:\Projects\opensource\ant-design-blazor\site\AntDesign.Docs\Services\DemoService.cs:line 42
         at AntDesign.Docs.Services.DemoService.GetMenuAsync() in D:\Projects\opensource\ant-design-blazor\site\AntDesign.Docs\Services\DemoService.cs:line 90
         at AntDesign.Docs.Shared.HeaderMenu.OnInitializedAsync() in D:\Projects\opensource\ant-design-blazor\site\AntDesign.Docs\Shared\HeaderMenu.razor.cs:line 29
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters)
         at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters)
         at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
         at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
         at AntDesign.Docs.Server.Pages.Pages__Host.<ExecuteAsync>b__11_1() in D:\Projects\opensource\ant-design-blazor\site\AntDesign.Docs.Server\Pages\_Host.cshtml:line 20
         at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
         at AntDesign.Docs.Server.Pages.Pages__Host.ExecuteAsync()
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
```

![image](https://user-images.githubusercontent.com/28926964/130759511-fcd35aab-90d0-479c-a336-ad91137a445f.png)


Thanks

**Comment by ElderJames** [comment]
Please rebuild the `AntDesign.Docs.Build` project, it would generate some files.

**Comment by shashikantx** [comment]
@ElderJames 
Sorry for my inactivity, got caught up in some work.

I was able to get around with this yesterday,
So I approached the problem as you suggested. I added a render fragment to AntInputComponentBase.cs

``` c#
        [Parameter]
        public RenderFragment Label { get; set; }
```

and Added label to render tree in `BuildRenderTree` of Input.cs
```c#
      if (Label != null)
      {
          builder.AddContent(34, Label);
      }
```

I was able to successfully add labels to Input via this method like this.

```c#
<div>
    <Input Placeholder="Basic usage" @bind-Value="@txtValue"  Label="_renderFragment"/>
    <br />
    <br />
    <Text>@txtValue</Text>
</div>
@code{
    string txtValue { get; set; }
    

    RenderFragment _renderFragment = __builder =>
    {
        <label>Test Label</label>
    };
}
```

But I see a problem in this approach, the developers still have to create a label component.  Why not go with the approach where label accepts string value? That way it is more easy to use and gives you more control on styling it.

It's a mere suggestion, If you want me to go ahead and make a PR for RenderFragment approach, I can do the same.

Thank you.

**Comment by knight1219** [comment]
Why not create 2 properties: `Label` and `LabelTemplate`. Label can be a string that's super simple to add and LabelTemplate can be the RenderFragment for more advanced customizations (like adding an icon to the label). That pattern is used throughout this library and would solve the issue it would seem

**Comment by ElderJames** [comment]
Yes, I am in favor of creating two parameters.

**Comment by shashikantx** [comment]
@knight1219 @ElderJames 

That is a good idea, I will add two properties then.

**Comment by shashikantx** [comment]
@anddrzejb  @ElderJames 
here is just a passing thought.

How about we use `PrefixTemplate` instead of `LabelTemplate`?

**Comment by shamseerahammedm** [comment]
+1

**Comment by ElderJames** [comment]
Now I'm working on the `SpaceCompact` component in  #3331  , and it can implement a label for input or other componets.
