### ISSUE TITLE
An error occurred while using <Select> with grouping (GroupName).

### ISSUE THREAD

**Issue by abberdeen** [ant-design-blazor/ant-design-blazor#2031]
###  Issue
When I use the `<Select>` control with grouping "enabled", that is, if you set a value in the GroupName field, the following error occurs. The error occurs when I click on the button to open the list (down arrow) or in other words, when I just open the list. 

Help me please figure out the reason for the error.

P.S. I am getting the same error with version 0.10.1.

### Source code

**Blazor markup:**
```csharp
   <Select DataSource="@AuditTypes"
                        @bind-Value="@_auditTypeId"
                        ValueName="@nameof(GroupListItem.Value)"
                        LabelName="@nameof(GroupListItem.Name)"
                        GroupName="@nameof(GroupListItem.Group)"
                        SortByLabel="@SortDirection.Ascending"
                        SortByGroup="@SortDirection.Ascending"
                        Placeholder="Select audit type" 
                        Size="small">
                </Select>
```
**Code behind:**
```csharp
private List<GroupListItem> AuditTypes { get; set; } = new ();
private int _auditTypeId { get; set; } 

public class GroupListItem
{
        public int Value { get; set; }
        public string Name { get; set; }
        public string Group { get; set; }
}
```

### Exceptions 
```csharp
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at AntDesign.Select.Internal.SelectOptionItem`2[[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[BlazorAdmin.Client.Models.GroupListItem, BlazorAdmin.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Ref()
   at AntDesign.Select`2.<ScrollToFirstSelectedItemAsync>d__198[[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[BlazorAdmin.Client.Models.GroupListItem, BlazorAdmin.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at AntDesign.Select`2.<OnOverlayVisibleChangeAsync>d__174[[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[BlazorAdmin.Client.Models.GroupListItem, BlazorAdmin.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at AntDesign.Internal.Overlay.Show(Nullable`1 overlayLeft, Nullable`1 overlayTop)
   at AntDesign.Internal.OverlayTrigger.Show(Nullable`1 overlayLeft, Nullable`1 overlayTop)
   at AntDesign.Internal.OverlayTrigger.OnTriggerClick()
   at AntDesign.Internal.OverlayTrigger.OnClickDiv(MouseEventArgs args)
   at AntDesign.SelectBase`2.<OnArrowClick>d__169[[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[BlazorAdmin.Client.Models.GroupListItem, BlazorAdmin.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
 

### Further technical details
- AntDesign Nuget Package version: 0.10.0 
- The IDE VS 2019 - 16.11.1

**Comment by abberdeen** [comment]
> Can you also post how does your `GroupListItem` class look like?

Oh sure. I have updated my post.

**Comment by anddrzejb** [comment]
Well...it is running on my dev version. Could you try nightly build?

Btw my basic tests only did empty `AuditTypes`.

**Comment by abberdeen** [comment]
@anddrzejb Thanks for your reply. I forgot to say that the error occurs when I click on the button to open the list (down arrow)

**Comment by anddrzejb** [comment]
I will check it out. However I might find time to do it on Monday.
