### ISSUE TITLE
Unhandled exception rendering component: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('domInfoHelper' was undefined).

### ISSUE THREAD

**Issue by shuangbaojun** [ant-design-blazor/ant-design-blazor#2139]
After upgrading 0.10.2, the error is as follows:

![image](https://user-images.githubusercontent.com/64063254/143805008-ef6255cb-6cf5-410c-83b9-dea1ab96a46d.png)

**Comment by anranruye** [comment]
please try to clear your broswer cache.

**Comment by dongfo** [comment]
@anranruye  that do not work

blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('domInfoHelper' was undefined).
      Error: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('domInfoHelper' was undefined).
          at http://localhost:5226/_framework/blazor.webassembly.js:1:328
          at Array.forEach (<anonymous>)
          at a.findFunction (http://localhost:5226/_framework/blazor.webassembly.js:1:296)
          at _ (http://localhost:5226/_framework/blazor.webassembly.js:1:2437)
          at http://localhost:5226/_framework/blazor.webassembly.js:1:3325
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (http://localhost:5226/_framework/blazor.webassembly.js:1:3306)
          at Object.Rt [as invokeJSFromDotNet] (http://localhost:5226/_framework/blazor.webassembly.js:1:59738)
          at _mono_wasm_invoke_js_blazor (http://localhost:5226/_framework/dotnet.6.0.0.8nqcpobx9h.js:1:193780)
          at wasm://wasm/00945abe:wasm-function[2588]:0x8065b
Microsoft.JSInterop.JSException: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('domInfoHelper' was undefined).
Error: Could not find 'AntDesign.interop.domInfoHelper.getWindow' ('domInfoHelper' was undefined).
    at http://localhost:5226/_framework/blazor.webassembly.js:1:328
    at Array.forEach (<anonymous>)
    at a.findFunction (http://localhost:5226/_framework/blazor.webassembly.js:1:296)
    at _ (http://localhost:5226/_framework/blazor.webassembly.js:1:2437)
    at http://localhost:5226/_framework/blazor.webassembly.js:1:3325
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (http://localhost:5226/_framework/blazor.webassembly.js:1:3306)
    at Object.Rt [as invokeJSFromDotNet] (http://localhost:5226/_framework/blazor.webassembly.js:1:59738)
    at _mono_wasm_invoke_js_blazor (http://localhost:5226/_framework/dotnet.6.0.0.8nqcpobx9h.js:1:193780)
    at wasm://wasm/00945abe:wasm-function[2588]:0x8065b
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[AntDesign.JsInterop.Window, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at AntDesign.AntComponentBase.<JsInvokeAsync>d__15`1[[AntDesign.JsInterop.Window, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at AntDesign.Sider.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
