### ISSUE TITLE
Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }

### ISSUE THREAD

**Issue by LiarMaiq** [ant-design-blazor/ant-design-blazor#2252]
Virtual Studio 2019
.NET 5.0

I use "dotnet new antdesign --host=server --full -o xxx" to create a project.
I got an error when I debug.

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Is there something wrong?

**Comment by ElderJames** [comment]
Thanks for contacting us @LiarMaiq .

This issue have been fixed in [ant-deisng-pro-blazor#](https://github.com/ant-design-blazor/ant-design-pro-blazor/pull/111). Please update the template. Or copy the _Host.cshtml file from https://github.com/ant-design-blazor/ant-design-pro-blazor/blob/master/.template.config/templates/server/Pages/_Host.cshtml
