### ISSUE TITLE
Steps component is trying to update state changes when disposed

### ISSUE THREAD

**Issue by Jtfk** [ant-design-blazor/ant-design-blazor#2411]
### Describe the bug

When the page is closed or refreshed, the `Step` component are trying to call the parent `Steps.ResetChildrenSteps()` which update the `GroupCurrentIndex` but the render is disposed.

### Steps to reproduce
1. create the `Steps` with `Step` components on a page
```razor
@* Taken from https://antblazor.com/en-US/components/steps#components-steps-demo-simple *@
<div>
    <Steps Current="1" Class="site-navigation-steps">
        <Step Title="Finished" Description="This is a description." />
        <Step Title="In Progress" Subtitle="Left 00:00:08" Description="This is a description." />
    </Steps>
</div>
```
2. Refresh or close the browser tab
3. There will be exceptions depending on the number of `Step`

### Exceptions
<details open>
  <summary>Click to expand</summary>

```
  warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
      System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at AntDesign.AntComponentBase.<InvokeStateHasChanged>b__9_0()
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Action workItem)
         at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Action workItem)
         at AntDesign.AntComponentBase.InvokeStateHasChanged()
         at AntDesign.Step.set_GroupCurrentIndex(Int32 value)
         at AntDesign.Steps.ResetChildrenSteps()
         at AntDesign.Step.Dispose(Boolean disposing)
         at AntDesign.AntComponentBase.Dispose()
         at AntDesign.Steps.Dispose(Boolean disposing)
         at AntDesign.AntComponentBase.Dispose()
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
      System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at AntDesign.AntComponentBase.<InvokeStateHasChanged>b__9_0()
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Action workItem)
         at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Action workItem)
         at AntDesign.AntComponentBase.InvokeStateHasChanged()
         at AntDesign.Step.set_GroupCurrentIndex(Int32 value)
         at AntDesign.Steps.ResetChildrenSteps()
         at AntDesign.Step.Dispose(Boolean disposing)
         at AntDesign.AntComponentBase.Dispose()
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'KmFDwVMlHt-O41VKrseE8TQ5RCMVGPXJiVpocVoAOiw'.
      System.AggregateException: Exceptions were encountered while disposing components. (Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.) (Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.)
       ---> System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at AntDesign.AntComponentBase.<InvokeStateHasChanged>b__9_0()
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Action workItem)
         at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Action workItem)
         at AntDesign.AntComponentBase.InvokeStateHasChanged()
         at AntDesign.Step.set_GroupCurrentIndex(Int32 value)
         at AntDesign.Steps.ResetChildrenSteps()
         at AntDesign.Step.Dispose(Boolean disposing)
         at AntDesign.AntComponentBase.Dispose()
         at AntDesign.Steps.Dispose(Boolean disposing)
         at AntDesign.AntComponentBase.Dispose()
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
         --- End of inner exception stack trace ---
       ---> (Inner Exception #1) System.ObjectDisposedException: Cannot process pending renders after the renderer has been disposed.
      Object name: 'Renderer'.
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.ProcessPendingRender()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at AntDesign.AntComponentBase.<InvokeStateHasChanged>b__9_0()
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Action workItem)
         at Microsoft.AspNetCore.Components.ComponentBase.InvokeAsync(Action workItem)
         at AntDesign.AntComponentBase.InvokeStateHasChanged()
         at AntDesign.Step.set_GroupCurrentIndex(Int32 value)
         at AntDesign.Steps.ResetChildrenSteps()
         at AntDesign.Step.Dispose(Boolean disposing)
         at AntDesign.AntComponentBase.Dispose()
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
```
</details>

### Further technical details
- AntDesign Nuget Package version: 0.10.3.1
- .NET SDK Version: 5.0.405
- Using Blazor server

**Comment by ElderJames** [comment]
have been fixed.
