### ISSUE TITLE
ReuseTabs: has An error when closing tag

### ISSUE THREAD

**Issue by liuhou-zhangliang** [ant-design-blazor/ant-design-blazor#2518]
my demo:

```
<div class="page">
    <div class="sidebar">
        <NavMenu />
    </div>

    <div class="main">
        <div class="top-row px-4">
            <a href="https://ant-design-blazor.gitee.io/zh-CN/docs/introduce" target="_blank" class="ml-md-auto"><Icon Type="github" />README</a>
        </div>
        <ReuseTabs Class="top-row px-4" TabPaneClass="content px-4" />
    </div>
</div>
```

I open a pages and close it there have some error:

blazor.webassembly.js:1 Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '16'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId')
   at Microsoft.JSInterop.JSRuntime.GetObjectReference(:5000/Int64 dotNetObjectId)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(:5000/JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (blazor.webassembly.js:1:3531)
    at Object.Ot [as endInvokeDotNetFromJS] (blazor.webassembly.js:1:60451)
    at Object.Rt [as invokeJSFromDotNet] (blazor.webassembly.js:1:59934)
    at _mono_wasm_invoke_js_blazor (dotnet.6.0.4.8qotm916vr.js:1:195300)
    at 00970c26:0x1a0fb
    at 00970c26:0xcac9
    at 00970c26:0xb9dc
    at 00970c26:0xabb22
    at 00970c26:0x6f935
    at 00970c26:0x6ffa2
endInvokeDotNetFromJS @ blazor.webassembly.js:1
Ot @ blazor.webassembly.js:1
Rt @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.6.0.4.8qotm916vr.js:1
$func219 @ 00970c26:0x1a0fb
$func167 @ 00970c26:0xcac9
$func166 @ 00970c26:0xb9dc
$func2810 @ 00970c26:0xabb22
$func1615 @ 00970c26:0x6f935
$func1619 @ 00970c26:0x6ffa2
$mono_wasm_invoke_method @ 00970c26:0x969b
Module._mono_wasm_invoke_method @ dotnet.6.0.4.8qotm916vr.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_BeginInvokeDotNet:19
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
b @ blazor.webassembly.js:1
invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ ant-design-blazor.js:1
blazor.webassembly.js:1 Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '20'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId')
   at Microsoft.JSInterop.JSRuntime.GetObjectReference(:5000/Int64 dotNetObjectId)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(:5000/JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (blazor.webassembly.js:1:3531)
    at Object.Ot [as endInvokeDotNetFromJS] (blazor.webassembly.js:1:60451)
    at Object.Rt [as invokeJSFromDotNet] (blazor.webassembly.js:1:59934)
    at _mono_wasm_invoke_js_blazor (dotnet.6.0.4.8qotm916vr.js:1:195300)
    at 00970c26:0x1a0fb
    at 00970c26:0xcac9
    at 00970c26:0xb9dc
    at 00970c26:0xabb22
    at 00970c26:0x6f935
    at 00970c26:0x6ffa2

**Comment by ElderJames** [comment]
fixed in #2738
