### ISSUE TITLE
Error after reloading a Page with TextArea - The JSON value could not be converted to System.Double. Path: $.lineHeight

### ISSUE THREAD

**Issue by thomas-biacsics** [ant-design-blazor/ant-design-blazor#2565]
### Steps to reproduce (please include code)

- Create Blazor WASM Project
- add new Page
- add Form with TextArea: <TextArea @bind-Value="@test" Rows="4" />
- Reload the page via browser
- An error occurs because of trying to JSON-serialize a NULL value into Double (properties of TextAreaInfo object)

### Exceptions (if any)

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to System.Double. Path: $.lineHeight | LineNumber: 0 | BytePositionInLine: 36.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Double. Path: $.lineHeight | LineNumber: 0 | BytePositionInLine: 36.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Double. Path: $.lineHeight | LineNumber: 0 | BytePositionInLine: 36.
 **---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.**
   at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
   at System.Text.Json.Utf8JsonReader.GetDouble()
   at System.Text.Json.Serialization.Converters.DoubleConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Double, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[AntDesign.TextArea.TextAreaInfo, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TextAreaInfo& value)
   at System.Text.Json.Serialization.JsonConverter`1[[AntDesign.TextArea.TextAreaInfo, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TextAreaInfo& value)
   at System.Text.Json.Serialization.JsonConverter`1[[AntDesign.TextArea.TextAreaInfo, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1[[AntDesign.TextArea.TextAreaInfo, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[AntDesign.TextArea.TextAreaInfo, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[AntDesign.TextArea.TextAreaInfo, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at AntDesign.AntComponentBase.<JsInvokeAsync>d__15`1[[AntDesign.TextArea.TextAreaInfo, AntDesign, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at AntDesign.TextArea.RegisterResizeEvents()
   at AntDesign.TextArea.OnFirstAfterRenderAsync()
   at AntDesign.AntComponentBase.OnAfterRenderAsync(Boolean firstRender)
   at AntDesign.Input`1.<OnAfterRenderAsync>d__166[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at AntDesign.TextArea.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Error: System.Text.Json.JsonException: The JSON value could not be converted to System.Single. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetSingle(Single& value)
   at System.Text.Json.Utf8JsonReader.GetSingle()
   at System.Text.Json.Serialization.Converters.SingleConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Single& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Single, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (https://localhost:7025/_framework/blazor.webassembly.js?v=1:1:3531)
    at Object.Rt [as endInvokeDotNetFromJS] (https://localhost:7025/_framework/blazor.webassembly.js?v=1:1:60566)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7025/_framework/blazor.webassembly.js?v=1:1:60049)
    at _mono_wasm_invoke_js_blazor (https://localhost:7025/_framework/dotnet.6.0.6.d7k7cs0bnw.js:1:195300)

AntDesign Version 0.11.0

**Comment by ElderJames** [comment]
Thanks for contacting us @thomas-biacsics .

I can't reproduce this problem right now. Please upgrade to 0.12.6 and provide a reproducible demo if you still have problems.
