### ISSUE TITLE
[0.12.0] ReuseTabsRouteView.GetPageInfo:page URL is error

### ISSUE THREAD

**Issue by shuaqq2004** [ant-design-blazor/ant-design-blazor#2630]
升级到AntDesign0.12.0无法打开登录页面/login
The login page /login cannot be opened when upgrading to AntDesign0.12.0

[16:04:32 WRN] Unhandled exception rendering component: Invalid URI: The format of the URI could not be determined.
{"EventId":{"Id":100,"Name":"ExceptionRenderingComponent"},"SourceContext":"Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer","TransportConnectionId":"jYAVA89d5CCALTbBubOihA","RequestId":"0HMK42JBSS8RE:00000002","RequestPath":"/_blazor","ConnectionId":"0HMK42JBSS8RE"}
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
  ###  at AntDesign.ReuseTabsRouteView.GetPageInfo(ReuseTabsPageItem pageItem, Type pageType, String url, Object page)
   at AntDesign.ReuseTabsRouteView.<>c__DisplayClass18_0.<CreateBody>b__1(Object ref)

```
//app.razor
<ReuseTabsRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />

//login.razor
@page "/login"
@layout PassportLayout
@attribute [ReuseTabsPage(Ignore = true)]
```
回滚0.11.0后正常
rollback 0.11.0 is normal

PS: AntDesign.ProLayout 0.10.6

**Comment by shuaqq2004** [comment]
[0.12.0--0830] 版本依旧报错， 但是报错内容变了。
```
[17:49:24 WRN] Unhandled exception rendering component: This operation is not supported for a relative URI.
{"EventId":{"Id":100,"Name":"ExceptionRenderingComponent"},"SourceContext":"Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer","TransportConnectionId":"T--KPO83xssfrEiLSnjY6g","RequestId":"0HMKADEOAJ09I:00000002","RequestPath":"/_blazor","ConnectionId":"0HMKADEOAJ09I"}
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_PathAndQuery()
   at AntDesign.ReuseTabsRouteView.GetPageInfo(ReuseTabsPageItem pageItem, Type pageType, String url, Object page)
   at AntDesign.ReuseTabsRouteView.<>c__DisplayClass18_0.<CreateBody>b__1(Object ref)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentReferenceCaptureFrame(DiffContext& diffContext, RenderTreeFrame& newFrame)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
[17:49:24 ERR] Unhandled exception in circuit 'krLQjMWmBL1L8wpwVmoUxF4LZLHALnPCLwUMXZXIvyQ'.
{"EventId":{"Id":111,"Name":"CircuitUnhandledException"},"SourceContext":"Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost","TransportConnectionId":"T--KPO83xssfrEiLSnjY6g","RequestId":"0HMKADEOAJ09I:00000002","RequestPath":"/_blazor","ConnectionId":"0HMKADEOAJ09I"}
System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_PathAndQuery()
   at AntDesign.ReuseTabsRouteView.GetPageInfo(ReuseTabsPageItem pageItem, Type pageType, String url, Object page)
   at AntDesign.ReuseTabsRouteView.<>c__DisplayClass18_0.<CreateBody>b__1(Object ref)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentReferenceCaptureFrame(DiffContext& diffContext, RenderTreeFrame& newFrame)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by shuaqq2004** [comment]
[0.12.1] fixed
