### ISSUE TITLE
back to  top  error

### ISSUE THREAD

**Issue by gitlsl** [ant-design-blazor/ant-design-blazor#294]
````
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'scrollTo' of null
      TypeError: Cannot read property 'scrollTo' of null
          at Object.n.BackTop (https://ant-design-blazor.github.io/_content/AntDesign/js/ant-design-blazor.js:1:4023)
          at https://ant-design-blazor.github.io/_framework/blazor.webassembly.js:1:9873
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://ant-design-blazor.github.io/_framework/blazor.webassembly.js:1:9841)
          at _mono_wasm_invoke_js_marshalled (https://ant-design-blazor.github.io/_framework/wasm/dotnet.3.2.0.js:1:171294)
          at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
          at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
          at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
          at interp_runtime_invoke (<anonymous>:wasm-function[5655]:0xf7391)
          at mono_jit_runtime_invoke (<anonymous>:wasm-function[5109]:0xddb3d)
Microsoft.JSInterop.JSException: Cannot read property 'scrollTo' of null
TypeError: Cannot read property 'scrollTo' of null
    at Object.n.BackTop (https://ant-design-blazor.github.io/_content/AntDesign/js/ant-design-blazor.js:1:4023)
    at https://ant-design-blazor.github.io/_framework/blazor.webassembly.js:1:9873
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://ant-design-blazor.github.io/_framework/blazor.webassembly.js:1:9841)
    at _mono_wasm_invoke_js_marshalled (https://ant-design-blazor.github.io/_framework/wasm/dotnet.3.2.0.js:1:171294)
    at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
    at interp_runtime_invoke (<anonymous>:wasm-function[5655]:0xf7391)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[5109]:0xddb3d)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x25ad450 + 0x0002c> in <filename unknown>:0 
  at AntDesign.AntComponentBase.JsInvokeAsync[T] (System.String code, System.Object[] args) <0x2545c58 + 0x000ea> in <filename unknown>:0 
  at AntDesign.BackTop.OnClick () <0x2bd8b08 + 0x000e2> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion (System.Threading.Tasks.Task task) <0x24c6080 + 0x000ee> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2454de8 + 0x000ca> in <filename unknown>:0 
````

在  `https://ant-design-blazor.github.io/zh-CN/components/backtop` 中测试点击 回到顶部按钮 无效, 出现上述错误

**Comment by ElderJames** [comment]
Thank you for report @gitlsl . We will fix it later.
