### ISSUE TITLE
Table PropertyColumn Filterable with TypeConverter throws NotImplementedException

### ISSUE THREAD

**Issue by michaelcsikos** [ant-design-blazor/ant-design-blazor#2949]
I have a simple class which wraps a string to sort them more naturally, e.g.
`File1.txt`
`File2.txt`
`File10.txt`
(The default string sort would display `File10.txt` before `File2.txt`)

I have implemented a `TypeConverter` to convert to and from `string`.

Adding `Filterable` to the `PropertyColumn` throws the following exception when I try to _apply_ a filter:
```
System.NotImplementedException: The method or operation is not implemented.
   at AntDesign.FilterExpression.FilterExpressionResolver`1.GetFilterExpression()
   at AntDesign.TableModels.FilterModel`1.FilterList[TItem](IQueryable`1 source)
   at AntDesign.TableModels.QueryModel`1.ExecuteQuery(IQueryable`1 query)
   at AntDesign.Table`1.InternalReload()
   at AntDesign.Table`1.ReloadAndInvokeChange()
   at AntDesign.Table`1.AntDesign.ITable.ReloadAndInvokeChange()
   at AntDesign.Column`1.FilterConfirm(Boolean isReset)
   at AntDesign.Column`1.<get_FilterToolTipSorter>b__145_10()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'Nrudtywd1lOhLn59zOqn10MwbnuPkNKXPxh3cwZ_W-0'.

System.NotImplementedException: The method or operation is not implemented.
   at AntDesign.FilterExpression.FilterExpressionResolver`1.GetFilterExpression()
   at AntDesign.TableModels.FilterModel`1.FilterList[TItem](IQueryable`1 source)
   at AntDesign.TableModels.QueryModel`1.ExecuteQuery(IQueryable`1 query)
   at AntDesign.Table`1.InternalReload()
   at AntDesign.Table`1.ReloadAndInvokeChange()
   at AntDesign.Table`1.AntDesign.ITable.ReloadAndInvokeChange()
   at AntDesign.Column`1.FilterConfirm(Boolean isReset)
   at AntDesign.Column`1.<get_FilterToolTipSorter>b__145_10()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by ElderJames** [comment]
Hello @michaelcsikos , I don't understand why you use TypeConverter. But I think you can use Filters properties:

```
  public TableFilter<string>[] nameFilters = new TableFilter<string>[] {
        new() { Text = "File1.txt", Value = "File1.txt" },
        new() { Text = "File2.txt", Value = "File2.txt" },
        new() { Text = "File10.txt", Value = "File10.txt" },
    };
```

**Comment by michaelcsikos** [comment]
I have a class which wraps a string to allow them to sort in a particular way. The default sort for strings is not what I want. The Ant  filters complain if I don't implement a type converter to string. To test it you could just declare a simple class:

```cs
public class Widget
{
    public string Value { get; set; }

    public override string ToString()
    {
        return Value;
    }
}
```

Without a type converter Ant will complain. Once you implement a type converter it still doesn't work, throwing the above exception.

**Comment by ElderJames** [comment]
I think it is the English component that identifies the type of TData without considering the converter.

```
        public static Type GetUnderlyingType<T>()
        {
            var type = typeof(T);
            Type targetType;
            if (type.GetTypeInfo().IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable<>))
            {
                targetType = Nullable.GetUnderlyingType(type);
            }
            else
            {
                targetType = type;
            }
            return targetType;
        }
```

I suggest that for now it's better to precast to string.

**Comment by michaelcsikos** [comment]
If I precast to a `string` it defeats the purpose of my `SortValueItem` wrapper class which sorts numbers naturally.

Is there a way to tell the column's automatic filter to call the context's object `ToString()` and allow the normal string filtering?

Or is there another way to set up a custom sort method for a column?

**Comment by michaelcsikos** [comment]
I see there is an example using `SorterCompare`. I will try that.

**Comment by michaelcsikos** [comment]
Using my own `SorterCompare` function works fine with `string` column. I have converted my business object properties to `string`.

**Comment by ElderJames** [comment]
That sounds good. Can you post your solution here?

**Comment by michaelcsikos** [comment]
The `StringNumberSortValueParser.ToSortValue()` extension method uses a `Regex` to pad out any numbers to help ensure they sort naturally. It optionally accepts a `SortValueCache` to help improve performance.

```cs
    public static class StringNumberSortValueParser
    {
        public static string ToSortValue(this string value, SortValueCache cache = null)
        {
            if (cache != null)
            {
                if (cache.TryGetValue(value, out string result))
                    return result;
            }

            var sortValue = Regex.Replace(value, "\\d+", x => x.Value.PadLeft(10, '0'));

            if (cache != null)
                cache[value] = sortValue;

            return sortValue;
        }
    }

    public class SortValueCache
        : Dictionary<string, string>
    {
    }
```

`ColumnStringNumberSort` inherits from `Column<string>` and defines the `SorterCompare` function. It uses a local `SortValueCache`.

```razor
@*ColumnStringNumberSort*@

@inherits Column<string>
@{
    base.BuildRenderTree(__builder);
}

@code
{
    protected override void OnInitialized()
    {
        SorterCompare = Compare;

        base.OnInitialized();
    }

    SortValueCache _sortValueCache = new SortValueCache();

    private int Compare(string a, string b)
    {
        if (a == null)
            return -1;

        if (b == null)
            return 1;

        var aSortValue = a.ToSortValue(_sortValueCache);
        var bSortValue = b.ToSortValue(_sortValueCache);

        return aSortValue.CompareTo(bSortValue);
    }
}

```
