### ISSUE TITLE
Modal Compoent throw JSException while set Draggable property

### ISSUE THREAD

**Issue by MarvelTiter** [ant-design-blazor/ant-design-blazor#3003]
### Describe the bug

```
Microsoft.JSInterop.JSException: t.addEventListener is not a function
TypeError: t.addEventListener is not a function
   at a.bindDrag (http://1ocalhost:5145/_content/AntDesign/js/ant-design-blazor.js:1:37823)
   at o,enableDraggable (http://ocalhost:5145/ content/AntDesign/is/ant-design-blazor.js:1:40472)
   at http://1ocalhost:5145/ framework/blazor.server.js:1:3501
   at new Promi se (<anonymous>)
   at kt.beginInyokeJSFromDotNet (http://1ocalhost:5145/ framework/blazor.server.js:1:3475)
   at http://localhost:5145/ framework/blazor.server.js:1:72077
   at Array.forEach (<anonymous>)
   at kt._invokeClientethod (http://1ocalhost:5145/_framework/blazor.server.js:1:72063)
   at kt.processIncomingData (http://1ocalhost:5145/_framework/blazor.server.js:1:70105)
   at connection.onreceive (http://ocalhost:5145/_framework/blazor.server.js:1:64508)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceld, String identifier, 0bjectl] args)
   at Microsoft.JSInterop.JSRuntimeExtensions,InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, 0bjectl] args)
   at AntDesign.AntComponentBase.JsInvokeAsync(String code, Objectl] args,
```

AntDesign Version ：0.13.3
Microsoft Edge Version： 108.0.1462.76
### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Hello @MarvelTiter , I can't reproduce the issue. Could you please provie a demo?
