### ISSUE TITLE
When using Table and set ScrollX in the case of server inside, it will throw an abnormal

### ISSUE THREAD

**Issue by SmRiley** [ant-design-blazor/ant-design-blazor#3199]
### Describe the bug
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
![image](https://user-images.githubusercontent.com/45205313/227475040-5279a151-5313-4f00-9fd8-f959a44f2ebf.png)
Although it does not affect use

**Comment by SmRiley** [comment]
new version fixed
