### ISSUE TITLE
Cannot be modified when multiple connections are made MenuRender by Basic Layout

### ISSUE THREAD

**Issue by lsx1994** [ant-design-blazor/ant-design-blazor#3201]
version:
antdesign.prolayout(0.14.4)

Open two browser connections at the same time, click TestLay, and one of them will report an error:
```
Error: System.InvalidOperationException: Unable to set property 'MenuRender' on object of type 'AntDesign.ProLayout.BasicLayout'. The error was: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
 ---> System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
   at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at AntDesign.ProLayout.BasicLayout.OnStateChanged()
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

Code:
```
AntDesign.ProLayout.BasicLayout MenuRender="@IsMenuRender"
    Logo="@("https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicRK.svg")"
    MenuData="_menuData">
    <ChildContent>
        <Button OnClick="TestLay">TestLay</Button>
        @Body
    </ChildContent>
    <FooterRender>
        <FooterView Copyright="2021 Ant Design Blazor" Links="Links"></FooterView>
    </FooterRender>
</AntDesign.ProLayout.BasicLayout>


@code
{
    void TestLay()
    {
        InvokeAsync(() =>
        {
            IsMenuRender = !IsMenuRender;
            StateHasChanged();
        });
    }
...
```

**Comment by michaelcsikos** [comment]
When will this bug fix be released?

**Comment by michaelcsikos** [comment]
I have had to remove `NavTheme="MenuTheme.Dark"` to stop this crash for now.
```razor
<AntDesign.ProLayout.BasicLayout>
    <HeaderContentRender>
        <BaseMenu Mode="MenuMode.Horizontal" NavTheme="MenuTheme.Dark" MenuData="MenuData">
```

**Comment by ElderJames** [comment]
@michaelcsikos Please update the prolayout to 0.14.4.1, thank you!

**Comment by michaelcsikos** [comment]
It's working, thanks!
