### ISSUE TITLE
No element is currently associated with component  XX

### ISSUE THREAD

**Issue by charleypeng** [ant-design-blazor/ant-design-blazor#3212]
Previously I was using v0.13.x,  recently I updated my program to latest v0.14.x, and get my project cleaned, rebuilt it and it shows the error below.
`blazor.webassembly.js?v=0.1.15:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: No element is currently associated with component 147
      Error: No element is currently associated with component 147
          at se.updateComponent (https://localhost:44324/_framework/blazor.webassembly.js?v=0.1.15:1:20261)
          at https://localhost:44324/_framework/blazor.webassembly.js?v=0.1.15:1:59545
          at Vt.Ke._internal.renderBatch (https://localhost:44324/_framework/blazor.webassembly.js?v=0.1.15:1:59917)
          at Object.Gt [as invokeJSFromDotNet] (https://localhost:44324/_framework/blazor.webassembly.js?v=0.1.15:1:62760)
          at Object.Ii (https://localhost:44324/_framework/dotnet.7.0.4.ojlstzkjtu.js:5:71922)
          at _mono_wasm_invoke_js_blazor (https://localhost:44324/_framework/dotnet.7.0.4.ojlstzkjtu.js:14:103886)
          at https://localhost:44324/_framework/dotnet.wasm:wasm-function[169]:0xc136
          at https://localhost:44324/_framework/dotnet.wasm:wasm-function[221]:0xe7a5
          at https://localhost:44324/_framework/dotnet.wasm:wasm-function[220]:0xce95
          at https://localhost:44324/_framework/dotnet.wasm:wasm-function[8115]:0x1a21ff
Microsoft.JSInterop.JSException: No element is currently associated with component 147
Error: No element is currently associated with component 147
    at se.updateComponent (https://localhost:44324/_framework/blazor.webassembly.js?v=0.1.15:1:20261)
    at https://localhost:44324/_framework/blazor.webassembly.js?v=0.1.15:1:59545
    at Vt.Ke._internal.renderBatch (https://localhost:44324/_framework/blazor.webassembly.js?v=0.1.15:1:59917)
    at Object.Gt [as invokeJSFromDotNet] (https://localhost:44324/_framework/blazor.webassembly.js?v=0.1.15:1:62760)
    at Object.Ii (https://localhost:44324/_framework/dotnet.7.0.4.ojlstzkjtu.js:5:71922)
    at _mono_wasm_invoke_js_blazor (https://localhost:44324/_framework/dotnet.7.0.4.ojlstzkjtu.js:14:103886)
    at https://localhost:44324/_framework/dotnet.wasm:wasm-function[169]:0xc136
    at https://localhost:44324/_framework/dotnet.wasm:wasm-function[221]:0xe7a5
    at https://localhost:44324/_framework/dotnet.wasm:wasm-function[220]:0xce95
    at https://localhost:44324/_framework/dotnet.wasm:wasm-function[8115]:0x1a21ff
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()`

Did I miss some thing to change as there is a breaking change for the latest version?

**Comment by ElderJames** [comment]
Hello @charleypeng , what component are you using in this page?

**Comment by charleypeng** [comment]
> Hello @charleypeng , what component are you using in this page?

Problem solved, I forgot to change to AuthorizerouteView for the reuse tab.
