### ISSUE TITLE
Table not working with abstract class

### ISSUE THREAD

**Issue by niedererfl** [ant-design-blazor/ant-design-blazor#3471]
### Describe the bug
It is not possible to create a table where TItem is an abstract class. 

### Steps to reproduce (please include code)
```csharp
<Table TItem="Book" DataSource="books">
    <PropertyColumn Title="Id" Property="c => c.ID"></PropertyColumn>
    <PropertyColumn Title="Bookname" Property="c => c.Name"></PropertyColumn>
</Table>

@code {
    public abstract class Book
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }

    private List<Book> books = new List<Book>();
}
```

### Exceptions (if any)
 System.TypeInitializationException: The type initializer for 'AntDesign.Table`1' threw an exception.
 ---> System.MemberAccessException: Cannot access member.
   at System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(Type type)
   at AntDesign.Table`1[[CanteenOrder.Shared.Models.OrderPosition, CanteenOrder.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]..cctor()
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type componentType)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
-->

### Further technical details
- AntDesign Nuget Package version: `0.16.0`
- `dotnet --info` : 
```sh
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.401\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

- IDE: Visual Studio Professional 2022 V17.7.4 using Blazor ASP.NET Core Hosted WebAssembly

**Comment by ElderJames** [comment]
Thanks for contacting us @niedererfl , currently we only support normal classes and interfaces. We will fix this by next version.

**Comment by ElderJames** [comment]
Hello @niedererfl , we have fixed this issue in 0.16.1!

**Comment by niedererfl** [comment]
Hello @ElderJames. In version 0.16.1 i can now set the TItem to an abstract class. but when i tried to start my appliction the table wont load. I can only see the spin component. If i set the TItem to a normal class it works fine.

**Comment by ElderJames** [comment]
Yes @niedererfl , this is because the table need to get the instance from DataSource.So it would spinning untill you the datasource got instance items.

**Comment by niedererfl** [comment]
Hello @ElderJames, the table keeps spinning until I add an element to the datasource, even if the datasource is instanced. When i remove the element from datasource it doesnt spin anymore.

**Comment by ElderJames** [comment]
You are right. Because it need to get an instance of TItem type from DataSource elements.

**Comment by niedererfl** [comment]
Okay I think I understand now. Thanks for the response.

**Comment by lmd-be** [comment]
@ElderJames  any workaround here? Seems odd, having to add an item to a list that might be empty. I think this issue is related to the bug I recently created: https://github.com/ant-design-blazor/ant-design-blazor/issues/3682

**Comment by lmd-be** [comment]
Problem is that right now when you request something from your datasource, but your datasource is empty, the table will continue spinning making the user think that the application is still working on something
