### ISSUE TITLE
NavigationManager issue when using in ModalService

### ISSUE THREAD

**Issue by MaggiGorengAyam** [ant-design-blazor/ant-design-blazor#3665]
### Describe the bug

When using ModalService, the OnOk which redirects to another page via NavigationManager causes a crash.

### Steps to reproduce
Using blazor server app.

Since introduction of 0.17.3 this issue has existed. Last working version is 0.17.2.
```
@page "/Temp"

@inject ModalService ModalService
@inject NavigationManager NavManager

<Button OnClick="TestModalService">Test Modal Service (broken)</Button>
<Button OnClick="TestModalService2">Test Modal Service 2 (working)</Button>
<Button OnClick="@(()=>{ _visible = true; })">
    Test Modal Component (working)
</Button>

<Modal Title="BasicModal"
       @bind-Visible="@_visible"
       OnOk="GoBack">
    <p>Test using Nav Manager in modal component of Ant Blazor</p>
</Modal>

@code {

    private bool _visible;

    private void TestModalService()
    {
        ModalService.Success(new ConfirmOptions()
            {
                Content = "Test using Nav Manager in modal service of ant blazor",
                OnOk = (e) => { GoBack(); return Task.CompletedTask; }
            });
    }

    private async void TestModalService2()
    {
        var confirm = await ModalService.SuccessAsync(new ConfirmOptions()
            {
                Content = "Test using Nav Manager in modal service 2 of ant blazor",
            });
        if (confirm)
        {
            GoBack();
        }
    }

    private void GoBack()
    {
        NavManager.NavigateTo("/");
    }

}
```

### Exceptions (if any)
Clicking on the first button "TestModalService", the following error will appear in the console output. This issue did not exist prior to 0.17.3.
```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: TypeError: Cannot read properties of null (reading 'removeChild')
      System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'removeChild')
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '3a6NJ6hfeXKOBKkVC0EArPRhnnrDGx7wl28AYHOp0jM'.
      System.AggregateException: One or more errors occurred. (TypeError: Cannot read properties of null (reading 'removeChild'))
       ---> System.InvalidOperationException: TypeError: Cannot read properties of null (reading 'removeChild')
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
         --- End of inner exception stack trace ---
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync(String code, Object[] args)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at AntDesign.AntComponentBase.JsInvokeAsync(String code, Object[] args)
         at AntDesign.Dialog.OnAfterRenderAsync(Boolean isFirst)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '3a6NJ6hfeXKOBKkVC0EArPRhnnrDGx7wl28AYHOp0jM'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at AntDesign.AntComponentBase.JsInvokeAsync(String code, Object[] args)
         at AntDesign.Dialog.OnAfterRenderAsync(Boolean isFirst)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### Further technical details
- AntDesign Nuget Package version: 0.17.4
- Include the output of `dotnet --info`
```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.30fce108

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.30fce108
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
```
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.8.5
Windows 10
```

**Comment by zxyao145** [comment]
@MaggiGorengAyam Hi, thank you for your feedback.  After 0.17.3, we added the handling of `NavigationManager.LocationChanged` to clean up some DOM,  which in some cases conflicted with the Blazor framework.

**Comment by MaggiGorengAyam** [comment]
@zxyao145 Noted. How will this work going forward? Is there a way this should be handled? Any reason why the async version works but not the non-async?

**Comment by zxyao145** [comment]
@MaggiGorengAyam 

Because the timing of triggering `NavigationManager.LocationChanged` is different between asynchronous and synchronous methods. 
Dialog will clean up the DOM when `NavigationManager.LocationChanged`, **In the synchronization method**, Dialogs first clean up the DOM, and then Blazor will clean it up; **In asynchronous method**, Blazor will first clean up the DOM, then the component is deleted, and the listening for  `NavigationManager.LocationChanged`  in the Dialog will become invalid.

A **temporary** solution is to cancel the closure of Confirm and hand over the clearance of DOM to Antd:
```c#
ModalService.Success(new ConfirmOptions()
    {
        Content = "Test using Nav Manager in modal service of ant blazor",
        OnOk = (e) =>
        {
+            e.Cancel = true;
            GoBack();
            return Task.CompletedTask;
        }
    });
```

This bug will be fixed as soon as possible.
