### ISSUE TITLE
BUG Report:  Cannot read properties of null (reading 'removeEventListener')

### ISSUE THREAD

**Issue by blackcatpolice** [ant-design-blazor/ant-design-blazor#3779]
https://github.com/ant-design-blazor/ant-design-blazor/blob/9f2e1255dc443f8bc965b65e2d3960614d405de4/components/upload/UploadButton.razor.cs#L232

In my maui blazor project.

> 73|2024-04-04T13:43:38.2870067+00:00|ERROR|1|App|Cannot read properties of null (reading 'removeEventListener')
TypeError: Cannot read properties of null (reading 'removeEventListener')
    at i.removeFileClickEventListener (https://0.0.0.0/_content/AntDesign/js/ant-design-blazor.js:1:36008)
    at https://0.0.0.0/_framework/blazor.webview.js:1:3050
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
    at https://0.0.0.0/_framework/blazor.webview.js:1:48020
    at EventTarget.<anonymous> (<anonymous>:7:62)
    at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:40770)
74|2024-04-04T13:43:38.2871373+00:00|ERROR|1|App|   at Microsoft.JSInterop.JS

I found this code in "UploadButton.razor.cs" . 

I don't know why .

I think sometimes when dispose button, but the button has already dispose.

So I think all the dispose element methods need check the element is alive

**Comment by ElderJames** [comment]
Thanks for contacting us @blackcatpolice , how did you use the Upload component?

**Comment by lukasvlcekcz** [comment]
Hi, I have the same problem. Here is how I define the button:
`<InputFile id="fileInput" OnChange="OnSelectFile" hidden />
<Upload>
    <label class="ant-btn" for="fileInput">
        <Icon Type="upload" />
        @_stringLocalizer[AppResource.SelectFile]
    </label>
</Upload>
`
Then I navigate to another page, and this Exception pops up.
Am I approaching this incorrectly, or is it a bug?
Thank you in advance for your cooperation.

**Comment by ElderJames** [comment]
Thanks for contacting us @blackcatpolice , we will fix it later.
