### ISSUE TITLE
Select Component JSException: Unable to focus an invalid element.

### ISSUE THREAD

**Issue by jxcproject** [ant-design-blazor/ant-design-blazor#3913]
I've set AutoFocus="@false", but in the case of dynamically creating and removing Select components, it will be reported as long as the operation frequency is faster

I checked the code, it called the SetInputFocusAsync method of the class SelectBase.cs
Now my temporary solution is to set the property Focused=true on reflection

```
            var focusedProperty = this._input.GetType().GetProperty("Focused",System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            if(focusedProperty != null)
            {
                focusedProperty.SetValue(this._input, true);
            }
```

### Describe the bug
![screenshots](https://github.com/ant-design-blazor/ant-design-blazor/assets/8786702/6936c896-8647-4cad-8e29-4e66f4057a1a)

### Exceptions (if any)
Unhandled Exception:
Microsoft.JSInterop.JSException: Unable to focus an invalid element.
Error: Unable to focus an invalid element.
    at Object.focus (http://localhost:5012/_framework/blazor.webassembly.js:1:32669)
    at http://localhost:5012/_framework/blazor.webassembly.js:1:2878
    at new Promise (<anonymous>)
    at b.beginInvokeJSFromDotNet (http://localhost:5012/_framework/blazor.webassembly.js:1:2835)
    at Object.vn [as invokeJSJson] (http://localhost:5012/_framework/blazor.webassembly.js:1:58849)
    at http://localhost:5012/_framework/dotnet.runtime.8.0.5.0exnpyrlhh.js:3:178364
    at Tl (http://localhost:5012/_framework/dotnet.runtime.8.0.5.0exnpyrlhh.js:3:179198)
    at http://localhost:5012/_framework/dotnet.native.wasm:wasm-function[349]:0x1fab4
    at http://localhost:5012/_framework/dotnet.native.wasm:wasm-function[245]:0x1bf5b
    at http://localhost:5012/_framework/dotnet.native.wasm:wasm-function[238]:0xf142
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AntDesign.Core.Extensions.JSRuntimeExtensions.FocusAsync(IJSRuntime jSRuntime, ElementReference target, Boolean preventScroll)
   at AntDesign.AntComponentBase.FocusAsync(ElementReference target, Boolean preventScroll)
   at AntDesign.SelectBase`2.<SetInputFocusAsync>d__217[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at AntDesign.Select`2.<OnInputFocusAsync>d__198[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at AntDesign.Select.Internal.SelectContent`2.<OnFocusInternal>d__122[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.ThreadPool.BackgroundJobHandler()

### Further technical details
- AntDesign 0.19.1

**Comment by ElderJames** [comment]
Thanks for contacting us @jxcproject , cloud you please provide a reproduce demo?

**Comment by jxcproject** [comment]
[BlazorApp1.zip](https://github.com/user-attachments/files/16519340/BlazorApp1.zip)
@ElderJames Thank you for your reply. The attachment above is a reproduction example.
