### ISSUE TITLE
Table Docs Do Not Load in 0.19.6

### ISSUE THREAD

**Issue by adamdriscoll** [ant-design-blazor/ant-design-blazor#4010]
I'm just viewing the table docs and notice the page does not render most of the tables. 

https://antblazor.com/en-US/components/table

Here is the console output from my browser. I tried Edge and Firefox. 

```
Service worker: Install
service-worker.js:27 Service worker: Activate
onpage-dialog.preload.js:310  Uncaught ReferenceError: browser is not defined
    at start (onpage-dialog.preload.js:310:5)
    at onpage-dialog.preload.js:319:1
    at onpage-dialog.preload.js:324:12
onpage-dialog-ui.preload.js:107  Uncaught ReferenceError: browser is not defined
    at 149 (onpage-dialog-ui.preload.js:107:3)
    at __webpack_require__ (onpage-dialog-ui.preload.js:1423:42)
    at onpage-dialog-ui.preload.js:1440:15
    at onpage-dialog-ui.preload.js:1681:3
    at onpage-dialog-ui.preload.js:1683:12
19[Deprecation] -ms-high-constrast is in the process of being deprecated. Please see <URL> for tips on updating to the new Forced Colors Mode standard.
blazor.webassembly.js:1 {"PageIndex":1,"PageSize":10,"StartIndex":0,"OffsetRecords":0,"SortModel":[{"Sort":null,"Priority":0,"FieldName":"Name","ColumnIndex":0},{"Sort":"descend","Priority":0,"FieldName":"Age","ColumnIndex":1},{"Sort":null,"Priority":0,"FieldName":"Address","ColumnIndex":2}],"FilterModel":[]}
blazor.webassembly.js:1 {"PageIndex":1,"PageSize":10,"StartIndex":0,"OffsetRecords":0,"SortModel":[{"Sort":null,"Priority":0,"FieldName":"Id","ColumnIndex":0},{"Sort":null,"Priority":0,"FieldName":"Name","ColumnIndex":1},{"Sort":null,"Priority":0,"FieldName":"Address","ColumnIndex":2},{"Sort":null,"Priority":0,"FieldName":"BirthDate","ColumnIndex":3},{"Sort":null,"Priority":0,"FieldName":"IsActive","ColumnIndex":4},{"Sort":null,"Priority":0,"FieldName":"Gender","ColumnIndex":5},{"Sort":null,"Priority":0,"FieldName":"Hobbies","ColumnIndex":6}],"FilterModel":[]}
blazor.webassembly.js:1 {"PageIndex":1,"PageSize":10,"StartIndex":0,"OffsetRecords":0,"SortModel":[{"Sort":null,"Priority":0,"FieldName":"Name","ColumnIndex":0},{"Sort":"descend","Priority":0,"FieldName":"Age","ColumnIndex":1},{"Sort":null,"Priority":0,"FieldName":"Address","ColumnIndex":2}],"FilterModel":[]}
blazor.webassembly.js:1 {"PageIndex":1,"PageSize":10,"StartIndex":0,"OffsetRecords":0,"SortModel":[{"Sort":null,"Priority":0,"FieldName":"Number","ColumnIndex":0},{"Sort":null,"Priority":0,"FieldName":"Name","ColumnIndex":1},{"Sort":null,"Priority":0,"FieldName":"Address","ColumnIndex":2},{"Sort":null,"Priority":0,"FieldName":"BirthDate","ColumnIndex":3},{"Sort":null,"Priority":0,"FieldName":"IsActive","ColumnIndex":4},{"Sort":null,"Priority":0,"FieldName":"Gender","ColumnIndex":5},{"Sort":null,"Priority":0,"FieldName":"Hobbies","ColumnIndex":6}],"FilterModel":[]}
blazor.webassembly.js:1 {"PageIndex":1,"PageSize":10,"StartIndex":0,"OffsetRecords":0,"SortModel":[{"Sort":null,"Priority":3,"FieldName":"chinese","ColumnIndex":1},{"Sort":null,"Priority":2,"FieldName":"math","ColumnIndex":2},{"Sort":null,"Priority":1,"FieldName":"english","ColumnIndex":3}],"FilterModel":[]}
dotnet.native.wasm:0x1245d3f  Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at dotnet.native.wasm:0x1245d3f
    at dotnet.native.wasm:0x1245d18
    at dotnet.native.wasm:0x4f11f3
    at dotnet.native.wasm:0x386696
    at dotnet.native.wasm:0x4f17b3
    at dotnet.native.wasm:0x4f18cc
    at dotnet.native.wasm:0x4f18cc
    at dotnet.native.wasm:0x4f18cc
    at dotnet.native.wasm:0x4f18cc
    at dotnet.native.wasm:0x4f18cc
onpage-dialog-ui.preload.js:107  Uncaught ReferenceError: browser is not defined
    at 149 (onpage-dialog-ui.preload.js:107:3)
    at __webpack_require__ (onpage-dialog-ui.preload.js:1423:42)
    at onpage-dialog-ui.preload.js:1440:15
    at onpage-dialog-ui.preload.js:1681:3
    at onpage-dialog-ui.preload.js:1683:12
```

**Comment by ElderJames** [comment]
Thanks for contacting us @adamdriscoll , we are fixing the doc in https://github.com/ant-design-blazor/ant-design-blazor/pull/4008

**Comment by adamdriscoll** [comment]
Loads for me now. Thank you!!
