### ISSUE TITLE
is the form component break change?

### ISSUE THREAD

**Issue by xinjiboy1234** [ant-design-blazor/ant-design-blazor#4077]
i am using the ant design blazor for develop a site , i am using the server render mode . 
and when i want to upgrade to 0.2 from 1.97 , there was some  error .
that is :
when i want to edit some field just like ( Metal Description, UOM , the source is under side) , there some errors occurred, and i read the document of 0.2, is the value binding must be change to @context.XXX?:
**Error Messsage:**

` Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at AntDesign.FormItem.AntDesign.Internal.IFormItem.ValidateField()
         at AntDesign.Form`1.RulesModeOnFieldChanged(Object sender, FieldChangedEventArgs args)
         at AntDesign.AntInputComponentBase`1.set_CurrentValue(TValue value)
         at AntDesign.AntInputComponentBase`1.set_CurrentValueAsString(String value)
         at AntDesign.Input`1.ChangeValue(Boolean force)
         at AntDesign.Input`1.OnChangeAsync(ChangeEventArgs args)
         at InvokeStub_Func`2.Invoke(Object, Span`1)
         at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'UbIX0IcNOIc4Q2epeS5Sffc2Cg1o4SJX5UZ7Ff_IIT4'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at AntDesign.FormItem.AntDesign.Internal.IFormItem.ValidateField()
         at AntDesign.Form`1.RulesModeOnFieldChanged(Object sender, FieldChangedEventArgs args)
         at AntDesign.AntInputComponentBase`1.set_CurrentValue(TValue value)
         at AntDesign.AntInputComponentBase`1.set_CurrentValueAsString(String value)
         at AntDesign.Input`1.ChangeValue(Boolean force)
         at AntDesign.Input`1.OnChangeAsync(ChangeEventArgs args)
         at InvokeStub_Func`2.Invoke(Object, Span`1)
         at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync(String code, Object[] args)
Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync(String code, Object[] args)`

**My Code:** 
`<FormItem Label="Metal Description">
                <Input @bind-Value="@_model.MetalDescription"/>
            </FormItem>
            <FormItem Label="EAU">
                <Input @bind-Value="@_model.EAU"/>
            </FormItem>
            <FormItem Label="UOM">
                <Input @bind-Value="@_model.UOM"/>
            </FormItem>
            <FormItem Label="Item Price" Rules="@(new FormValidationRule[] { new() { Type = FormFieldType.Number, Required = true } })">
                <Input @bind-Value="@_model.ItemPrice"/>
            </FormItem>`

**Comment by xinjiboy1234** [comment]
![image](https://github.com/user-attachments/assets/eaf8f134-200b-437d-93c6-ef40bdaee462)
 i think i know what is happened, when use the rule validation, must be add the rules for all of form items. it is bug? or it is designed like this?

**Comment by ElderJames** [comment]
Thanks for contacting us @xinjiboy1234 , this seems like a bug,  I will fix it ASAP.

**Comment by michaelcsikos** [comment]
I am getting a similar exception:
```
NullReferenceException: Object reference not set to an instance of an object.
AntDesign.Form<TModel>.RulesModeOnValidationRequested(object sender, ValidationRequestedEventArgs args)
Microsoft.AspNetCore.Components.Forms.EditContext.Validate()
Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)
Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.<WaitForNonStreamingPendingTasks>g__Execute|38_0()
Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext+<>c+<<InvokeAsync>b__10_0>d.MoveNext()
Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by ElderJames** [comment]
Hello @xinjiboy1234  @michaelcsikos  , please try 0.20.0.2 .

**Comment by michaelcsikos** [comment]
Thanks, seems to be working.
