### ISSUE TITLE
Table change DataSource, ReloadData with querymodel throws exception

### ISSUE THREAD

**Issue by rtrocmn** [ant-design-blazor/ant-design-blazor#4322]
When changing the DataSource on a Table and loading a QueryModel using ReloadData an exception is thrown.
It seems like the column info is out dated when the function ReloadData is invoked, is there a proper way to change the DataSource and load a (default) QueryModel ?

### Steps to reproduce
Press button "Switch Datasource" to change datasource and invoke ReloadData.

```
@using AntDesign.Filters
@using AntDesign.TableModels
@inject ILogger<TablePage> logger
@page "/table"

<Button OnClick="SwitchDS">Switch Datasource</Button>
<Table @ref="table"
       TItem="Dictionary<string, object>"
       DataSource="@data"
       Loading="loading"
       Size="TableSize.Small"
       AutoHeight
       HidePagination
       EnableVirtualization
       Resizable>
    @if (toggleDataSource)
    {
        <Column TData="int" DataIndex="['Id']" Title="Id" Sortable Ellipsis Filterable />
        <Column TData="string" DataIndex="['Name']" Title="Name" Sortable Ellipsis Filterable />
        <Column TData="DateTime" DataIndex="['DateOfBirth']" Title="DateOfBirth" Sortable Ellipsis Filterable />
        <Column TData="string" DataIndex="['Address']" Title="Address" Sortable Ellipsis Filterable />
        <Column TData="string" DataIndex="['City']" Title="City" Sortable Ellipsis Filterable />
        <Column TData="bool" DataIndex="['IsMember']" Title="IsMember" Sortable Ellipsis Filterable />
    }
    else
    {
        <Column TData="int" DataIndex="['Id']" Title="Id" Sortable Ellipsis Filterable />
        <Column TData="string" DataIndex="['Brand']" Title="Brand" Sortable Ellipsis Filterable />
        <Column TData="string" DataIndex="['Product']" Title="Product" Sortable Ellipsis Filterable />
        <Column TData="DateTime" DataIndex="['DateOfPurchase']" Title="DateOfPurchase" Sortable Ellipsis Filterable />
        <Column TData="bool" DataIndex="['IsPayed']" Title="IsPayed" Sortable Ellipsis Filterable />
    }
</Table>

@code {
    ITable table;
    IEnumerable<Dictionary<string, object>>? data;
    bool toggleDataSource = false;
    bool loading = false;

    protected override void OnInitialized()
    {
        LoadData();
    }


    private void LoadData()
    {
        loading = true;

        if (toggleDataSource)
        {
            data = Enumerable.Range(0, 100).Select(i =>
                    new Dictionary<string, object>(
                        [
                            new KeyValuePair<string, object>("Id", i),
                            new KeyValuePair<string, object>("Name", $"John Doe {i}"),
                            new KeyValuePair<string, object>("DateOfBirth", DateTime.Now.AddDays(-i)),
                            new KeyValuePair<string, object>("Address", $"Street {i}"),
                            new KeyValuePair<string, object>("City", $"City {i}"),
                            new KeyValuePair<string, object>("IsMember", (i % 2 == 0)),
                        ])
                   ).ToArray();
        }
        else
        {
            data = Enumerable.Range(0, 100).Select(i =>
                    new Dictionary<string, object>(
                        [
                            new KeyValuePair<string, object>("Id", i),
                            new KeyValuePair<string, object>("Brand", $"John Deer {i}"),
                            new KeyValuePair<string, object>("Product", $"Product {i}"),
                            new KeyValuePair<string, object>("DateOfPurchase", DateTime.Now.AddDays(-i)),
                            new KeyValuePair<string, object>("IsPayed", (i % 2 == 0)),
                        ])
                   ).ToArray();
        }

        loading = false;
    }

    private void SwitchDS()
    {
        toggleDataSource = !toggleDataSource;
        LoadData();

        try
        {
            QueryModel<Dictionary<string, object>> querymodel;
            if (toggleDataSource)
            {
                querymodel = new QueryModel<Dictionary<string, object>>(1, data?.Count() ?? 0, 1,
                    new List<ITableSortModel>() { },
                    new List<ITableFilterModel>() {
                        new FilterModel<bool>(
                            5,
                            "IsMember",
                            ["True"],
                            new List<TableFilter>() {
                                new TableFilter("Waar", true, true, TableFilterCompareOperator.Equals, TableFilterCondition.Or )
                            })
                    });
            }
            else
            {
                querymodel = new QueryModel<Dictionary<string, object>>(1, data?.Count() ?? 0, 1,
                    new List<ITableSortModel>() { },
                    new List<ITableFilterModel>() {
                        new FilterModel<bool>(
                            4,
                            "IsPayed",
                            ["False"],
                            new List<TableFilter>() {
                                new TableFilter("OnWaar", false, true, TableFilterCompareOperator.Equals, TableFilterCondition.Or )
                            })
                    });
            }

            table.ReloadData(querymodel);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Applying default filter failed.");
        }
    }
}
```

### Exceptions
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
         at System.Collections.Generic.List`1.get_Item(Int32 index)
         at AntDesign.Table`1.ReloadData(QueryModel queryModel)

### Further technical details
- AntDesign Nuget Package version 1.0
- .Net 8.0.10

**Comment by ElderJames** [comment]
This is beacuse the ReloadData was call before the changing of columns.

![image](https://github.com/user-attachments/assets/874ac6b6-ea08-40cf-8b0e-9868f6430043)
![image](https://github.com/user-attachments/assets/2d4f4b51-14de-4bbc-b914-56f5db1ac237)

**Comment by ElderJames** [comment]
Please try to give some time for changing columns before reload the table.

```diff
  private async Task SwitchDS()
  {
      toggleDataSource = !toggleDataSource;

+      StateHasChanged();
+      await Task.Delay(1000);

      LoadData();

...the rest code...
}
```
