### ISSUE TITLE
[form] form.reset() 异常

### ISSUE THREAD

**Issue by yuanxiongwei** [ant-design-blazor/ant-design-blazor#562]
在modal中的表单，使用form.reset 异常

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback`1.InvokeAsync(TValue arg)
   at AntDesign.Button.HandleOnClick(MouseEventArgs args)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

```

```
@page "/grades"
@page "/grades/{PageIndex:int}"

<Card>
    <Row Justify="space-between" Class="table-toolbar">
        <AntDesign.Col>
            <Title Level="4">年级管理</Title>
        </AntDesign.Col>
        <AntDesign.Col>
            <AuthorizeView Policy="@Policies.GradeEdit">
                <Button Type="@ButtonType.Primary" Icon="plus" OnClick="@HandleAddGrade">新增年级</Button>
            </AuthorizeView>
        </AntDesign.Col>
    </Row>
</Card>


<Modal Title="@("设置年级信息")" Visible="@editVisible" MaskClosable="false" OkText="@("保存")" CancelText="@("取消")" OnOk="@HandleSave" OnCancel="@HandleCancel" ConfirmLoading="saveLoading">
    <Form Model="@model" @ref="@form" LabelCol="new ColLayoutParam { Span = 4 }" WrapperCol="new ColLayoutParam { Span = 20 }" Name="staffForm" OnFinish="OnFinish" OnFinishFailed="OnFinishFailed">
        <FormItem Label="名称">
            <Input @bind-Value="@context.GradeName" />
        </FormItem>
        <FormItem Label="状态">
            <RadioGroup @bind-Value="@context.Status">
                <Radio Value="0">禁用</Radio>
                <Radio Value="1">正常</Radio>
            </RadioGroup>
        </FormItem>
    </Form>
</Modal>

@code{
    [Parameter]
    public int PageIndex { get; set; }

    bool editVisible = false;
    bool saveLoading = false;
    bool tableLoading = false;
    Form<GradeModel> form;
    ITable table;

    GradeModel model = new GradeModel();

    private async Task OnFinish(EditContext editContext)
    {
        //通过表单验证

        
    }

    private async Task OnFinishFailed(EditContext editContext)
    {

    }

    private void HandleSave(MouseEventArgs e)
    {
        saveLoading = true;
        form.Submit();

    }

    private void HandleCancel(MouseEventArgs e)
    {
        saveLoading = false;
        editVisible = false;
    }


    public void HandleAddGrade()
    {
        form.Reset();
        //model = new GradeModel();
        model.Status =1;
        editVisible = true;
    }


    protected override async Task OnInitializedAsync()
    {
    }


    void HandleChangePage(PaginationEventArgs args)
    {
        NavigationManager.NavigateTo($"grades/{args.PageIndex}");
    }

    protected override async Task OnParametersSetAsync()
    {
        try
        {
            tableLoading = true;
        }
        finally
        {
            tableLoading = false;
        }
    }


    public class GradeModel
    {
        public string GradeName { get; set; }
        public int Status { get; set; }
    }
}
```

还有一个问题，表单reset应该只是恢复初始化表单的数据，至于 到底是先赋值再reset，还是reset后再赋值or new model都应该不影响才正常。

**Comment by ElderJames** [comment]
model中的form需要时间来实例化，未实例化时`Form<GradeModel> form==null` ,所以才报错。建议在 modalserivce 中使用模板。
