### ISSUE TITLE
random errors when using InputNumber in Modal 

### ISSUE THREAD

**Issue by Seanxwy** [ant-design-blazor/ant-design-blazor#639]
在domal的form中使用inputnumber随机出错，每次都出错都是在操作输入inputnumber组件数值的时候。
The random error occurs in domal form when updating `inputnumber`.

```
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Int32. Path: $.scrollTop | LineNumber: 0 | BytePositionInLine: 149.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.scrollTop | LineNumber: 0 | BytePositionInLine: 149.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadValueCore(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
   at AntDesign.Internal.Overlay.Show(Nullable`1 overlayLeft, Nullable`1 overlayTop)
   at AntDesign.Internal.Overlay.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by ElderJames** [comment]
Hi @Seanxwy , could you please test in the latest version 0.7.1 to see if there are still problems?

**Comment by anddrzejb** [comment]
What is "domal"?

**Comment by ElderJames** [comment]
He meat Modal 😂

**Comment by anddrzejb** [comment]
Oh... Because the title was corrected, I thought it had a meaning. Now it is clear.
