### ISSUE TITLE
ModalService.CreateModal throws error

### ISSUE THREAD

**Issue by tiansfather** [ant-design-blazor/ant-design-blazor#807]
### Describe the bug
ModalService.CreateModal throws error
### Steps to reproduce (please include code)
just call this code
await ModalService.CreateModalAsync(new ModalOptions()
                    {
                        Title = "test"
                    });

### Exceptions (if any)
Unhandled exception rendering component: Delegate to an instance method cannot have null 'this'.
System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at AntDesign.ModalContainer.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

### Further technical details
- AntDesign Nuget Package version 0.4.1 or 0.5.0-nightly

**Comment by ElderJames** [comment]
Thank you for contacting us @tiansfather .

It is fixed via #809 . 

If there also have any problems, just feel free to create another issue to tell us.
