### ISSUE TITLE
Unhandled exception in circuit

### ISSUE THREAD

**Issue by kienboostml** [ant-design-blazor/ant-design-blazor#827]
### Describe the bug
Unhandled exception in circuit

### Exceptions (if any)

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at AntDesign.AntComponentBase.JsInvokeAsync[T](String code, Object[] args)
   at AntDesign.Row.<>c__DisplayClass35_0.<<SetGutterStyle>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at AntDesign.EnumerableExtensions.ForEachAsync[T](IEnumerable`1 items, Func`2 func)
   at AntDesign.Row.SetGutterStyle()
   at AntDesign.Row.OnResize(Object o)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

### Further technical details

- AntDesign Nuget Package version: 0.3.0
- dotnet: Version:   3.1.101

**Comment by ElderJames** [comment]
Thank you for contacting us @kienboostml 
Please update to 0.4.1 and try again.

**Comment by ElderJames** [comment]
Thank you for contacting us @kienboostml 
Please update to 0.4.1 and try again.

**Comment by kienboostml** [comment]
Thanks, I'll upgrade and retest
