### ISSUE TITLE
[New Select] @bind-value does not select the correct item

### ISSUE THREAD

**Issue by NPadrutt** [ant-design-blazor/ant-design-blazor#856]
### Describe the bug
NOTE: I'm using the new select 
I try to bind the value to a Select. My expectation would be, that the item with the corresponding value is selected and displayed, but it is empty.

```
<Select DataSource="Customers"
                    DefaultActiveFirstItem="false"
                    ValueName="@nameof(CustomerDto.CustomerId)"
                    LabelName="@nameof(CustomerDto.CustomerName)"
                    @bind-Value="@context.CustomerId"
                    OnSelectedItemChanged="@(item => context.CustomerId = item.CustomerId)"
                    EnableSearch
                    AllowClear />
```

When I use DefaultValue it does show the value correctly when the view is displayed, but I do get an error on the console telling me that I should use @bind-value

```
<Select DataSource="Customers"
                    DefaultActiveFirstItem="false"
                    ValueName="@nameof(CustomerDto.CustomerId)"
                    LabelName="@nameof(CustomerDto.CustomerName)"
                    DefaultValue="@context.CustomerId"
                    OnSelectedItemChanged="@(item => context.CustomerId = item.CustomerId)"
                    EnableSearch
                    AllowClear />

```

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Please use @bind-Value in the control with generic type `System.Nullable`1[System.Guid]`.
System.InvalidOperationException: Please use @bind-Value in the control with generic type `System.Nullable`1[System.Guid]`.
   at AntDesign.FormItem.AntDesign.Internal.IFormItem.AddControl[Nullable`1](AntInputComponentBase`1 control)
   at AntDesign.AntInputComponentBase`1[[System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnInitialized()
   at AntDesign.Select`2[[System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[ApplySupportTool.Shared.Dto.Customer.CustomerDto, ApplySupportTool.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

I'm a bit unsure if that is actually the intended usage. the @bind-Value didn't seem to work for me in the sense of writing to the model either so I had to use the OnSelectedItemChanged. So maybe binding is just not supported here?

### Further technical details
- AntDesign Nuget Package version: 0.5.0-nightly-2011281001
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS on Windows 10

**Comment by NPadrutt** [comment]
So. In the end it worked with the following: 

```
<Select DataSource="Customers"
                            DefaultActiveFirstItem="false"
                            ValueName="@nameof(CustomerDto.CustomerId)"
                            LabelName="@nameof(CustomerDto.CustomerName)"
                            @bind-Value="@context.CustomerId"
                            EnableSearch
                            AllowClear />
```

Not sure why it didn't before to be honest.

**Comment by ldsenow** [comment]
Although the issue has been closed, I have question here is why I have to use @bind-Value? 

Cant I use Value=@Value and ValueChanged=@ValueChanged? Is there a reason?

I create a custom component which wraps Select control and set the props as above. It gives me error Unhandled exception rendering component: Please use @bind-Value in the control with generic type....

**Comment by ElderJames** [comment]
Hi @ldsenow ,please create another issue.
