### ISSUE TITLE
AntRangePicker控件选择报错

### ISSUE THREAD

**Issue by CYTings** [ant-design-blazor/ant-design-blazor#88]
blazor.server.js:15 [2020-04-29T15:08:37.853Z] Error: System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
   at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at AntBlazor.AntDatePicker.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
e.log @ blazor.server.js:15
C @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1
blazor.server.js:1 [2020-04-29T15:08:37.857Z] Information: Connection disconnected.
9blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at e.send (blazor.server.js:1)
    at e.sendMessage (blazor.server.js:1)
    at e.sendWithProtocol (blazor.server.js:1)
    at e.send (blazor.server.js:1)
    at blazor.server.js:8
    at Object.t.dispatchEvent (blazor.server.js:8)
    at blazor.server.js:8
    at e.onEvent (blazor.server.js:8)
    at e.onGlobalEvent (blazor.server.js:8)
e.send @ blazor.server.js:1
e.sendMessage @ blazor.server.js:1
e.sendWithProtocol @ blazor.server.js:1
e.send @ blazor.server.js:1
(anonymous) @ blazor.server.js:8
t.dispatchEvent @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
e.onGlobalEvent @ blazor.server.js:8
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at e.send (blazor.server.js:1)
    at e.sendMessage (blazor.server.js:1)
    at e.sendWithProtocol (blazor.server.js:1)
    at e.send (blazor.server.js:1)
    at Object.beginInvokeDotNetFromJS (blazor.server.js:8)
    at c (blazor.server.js:8)
    at e.invokeMethodAsync (blazor.server.js:8)
    at o (interop.ts:40)
e.send @ blazor.server.js:1
e.sendMessage @ blazor.server.js:1
e.sendWithProtocol @ blazor.server.js:1
e.send @ blazor.server.js:1
beginInvokeDotNetFromJS @ blazor.server.js:8
c @ blazor.server.js:8
e.invokeMethodAsync @ blazor.server.js:8
o @ interop.ts:40

**Comment by mutouzdl** [comment]
有重新的步骤吗？

**Comment by mutouzdl** [comment]
我重现了，server版会报错，我看看

**Comment by CYTings** [comment]
好的，十分感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 笨木头 <notifications@github.com&gt;
发送时间: 2020年4月30日 07:31
收件人: ant-design-blazor/ant-design-blazor <ant-design-blazor@noreply.github.com&gt;
抄送: CYTings <306572180@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ant-design-blazor/ant-design-blazor] AntRangePicker控件选择报错 (#88)





 
我重现了，server版会报错，我看看
